"""Cable routing profiles for the proud family and skeletal Obi-Wan.

``LX_ROUTING_PROFILE=proud`` (R6P, the default) is the subtractive
route used by B2/C7/V0/V1 and, with a keyed terminal handoff, V1L.  Its
standard UM main follows the proven outer
U22 arc, returns through the broad lower neck, and then turns through a
true R14 three-dimensional elbow to the rear outlet at (33.45, 301.49).
The old planar-main/vertical-cylinder 90 degree collision is gone: the
complete handoff is one continuous sweep.  The route is D8.2 end to end,
raising nominal radial slack around the estimated D7 cable from 0.4 to
0.6 mm.  The outlet bearing is 297.4 degrees from the MU center: still
between the lower screws, but laterally clear of the conservative 283
degree Faston pull envelope and its rear cable continuation.

V1L keeps the same upstream R6P route but refits its terminal plan span
into a second G1 R14 handoff.  The center of that bore at V1L's physical
rear plane z=6.8 is exactly 60.0 mm from the MU center on the 283-degree
terminal axis.  This exception is selected explicitly by the V1L split
builder; every other proud-family builder retains the standard outlet.

``LX_ROUTING_PROFILE=obiwan`` (R6F) selects the isolated two-carrier
platform. The LM lead is a short free span with no printed duct. The UM
passage is printed only in LM; the shared-tweeter passage is printed only in
LM/UM. Those printed-owner spans are generated by
``top_baffle_nd25fw4_obiwan_route`` with continuous 0.8 mm minimum skins and
smooth, fully covered local Z bumps around crossed insert envelopes. UM then
floats behind its carrier and T floats behind the tweeter crescent. There is
no detachable external raceway or printed Obi-Wan grommet.

Within R6P, the LM and tweeter routes retain their established locations.
The LM rear bore is retained because the reported D7-in-D7.8 pinch concerned
the UM route. The proud R14 handoff and complete Obi-Wan physical centerlines,
including their intentional free spans, are checked by ``test_clearances.py``
and ``test_obiwan_r6f.py`` using eroded-outline containment and full-centerline
curvature rather than horizontal gaps.
"""

from __future__ import annotations

import math
import os

from build123d import (
    Circle,
    Cylinder,
    Line,
    Plane,
    Polyline,
    Pos,
    Rot,
    Spline,
    ThreePointArc,
    Wire,
    loft,
    make_face,
    sweep,
)

from top_baffle_nd25fw4 import (
    STAND_FOOT,
    UM_CUTOUT,
    UM_TERMINAL_CLOCK_DEG,
)

ROUTING_PROFILE = os.environ.get("LX_ROUTING_PROFILE", "proud").lower()
if ROUTING_PROFILE not in {"proud", "obiwan"}:
    raise ValueError(
        "LX_ROUTING_PROFILE must be 'proud' or 'obiwan', got "
        f"{ROUTING_PROFILE!r}"
    )
ROUTING_REV = {"proud": "R6P", "obiwan": "R6F"}[ROUTING_PROFILE]

LM_Y = 200.981
UM_Y = 366.081

# Duct plane depth per route -- ALL in the front half (front-datum):
# LM/UM O8.2 span z 8.45..16.65, TS 8.5..14.5 (round) /
# 8.25..12.65 (vase oval). Floors stay >=1.6 above the thin-family
# rear plane (z=6.8) except the oval's 1.45 -- the price of passing
# under the MU10 flange seat (z=14.3) with 1.65 to spare above.
DUCT_Z = {"lm": 12.55, "um": 12.55, "ts": 11.5}
LANE_OFFSET = 5.11  # TS lane center this far inside the vase wall lines

# The unified front-biased transverse-magnet plane brings the lower-left
# station into the TS duct's source-Z window in every stock/slim variant.
# Keep the complete D6 lumen and immutable magnet host by moving only this
# short span 0.60 mm toward x=0.  Exact BREP screening leaves 0.7919 mm from
# cavity void to duct and effectively zero (<0.00002 mm3) intersection with
# the helper's complete 0.60-mm-margin required land. Smoothstep ramps make
# the nudge tangent-continuous at both ends; the minimum spline bend radius
# remains >4.89 mm against the 4.5-mm release floor.
TS_ROUTE_STANDARD = "standard"
TS_ROUTE_CAPTIVE = "captive_keepout"
TS_CAPTIVE_NUDGE_MAX_MM = 0.60
TS_CAPTIVE_NUDGE_KNOTS = (
    (313.202641, 0.00),
    (317.145618, 0.30),
    (320.500000, 0.60),
    (324.000000, 0.60),
    (327.500000, 0.30),
    (330.800000, 0.00),
)

# LM carries 2 x 2.5 mm^2 (twisted ~O7.8) -> O8.2. UM carries a twisted
# 2 x 2.0 mm^2 pair (~O7.0) -> O8.2 (0.6 radial nominal slack). TS
# carries BOTH tweeter pairs side by side (~5.2 across) -> O6.0, the
# largest bore the notch corridor between the D82 rim and the vase
# chamfer admits.
CABLE_D = {"lm": 8.2, "um": 8.2, "ts": 6.0}

# Proud-family TS vase stretch: flattened oval through the thin V1/V1L
# vase corridor. W6.6 x H4.4 at zc=10.45: 1.65 under the former
# seat, 1.45 over the thin rear plane (z=6.8), and W/2=3.3 threads the
# notch corridor (>=1.84 to the D82 rim) and the vase lane (1.81 to
# the outline). The two AWG24 pairs ride side by side (~5.2 x 2.6).
# Morphs are y-parameterized (the vase path is y-monotone there):
# round O6.0 z=11.5 below y=316 and above y=425.5, full oval between
# y=330 and y=417.5, linear in the morph bands. The tube is fully
# dropped before it comes within 1.6 of the ring rim on both sides
# (rim crossings at plan dist 49.3 about (0, UM_Y): y~334 / ~415.5),
# and is round again before piercing the scallop rim (~429).
TS_OVAL = {"w2": 3.3, "h2": 2.2, "zc": 10.45,
           "y_in": (316.0, 330.0), "y_out": (417.5, 425.5)}


def ts_section(y):
    """(w2, h2, zc) of the TS duct section at height y: the oval drop
    under the MU10 flange seat, round O6.0 z=11.5 elsewhere. The duct
    cutter and route_points z both derive from this single law."""
    rw2, rh2, rzc = CABLE_D["ts"] / 2.0, CABLE_D["ts"] / 2.0, DUCT_Z["ts"]
    (yi0, yi1), (yo0, yo1) = TS_OVAL["y_in"], TS_OVAL["y_out"]
    ow2, oh2, ozc = TS_OVAL["w2"], TS_OVAL["h2"], TS_OVAL["zc"]
    if y <= yi0 or y >= yo1:
        return rw2, rh2, rzc
    if yi1 <= y <= yo0:
        return ow2, oh2, ozc
    if y < yi1:                       # entry morph
        f = (y - yi0) / (yi1 - yi0)
    else:                             # exit morph (f runs 1 -> 0)
        f = (yo1 - y) / (yo1 - yo0)
    return (rw2 + f * (ow2 - rw2), rh2 + f * (oh2 - rh2),
            rzc + f * (ozc - rzc))


def _with_z(pts2d, knots):
    """Attach z to 2D route points by cumulative path length, piecewise-
    linear between (s, z) knots (the spline smooths knot corners)."""
    out, s_acc = [], 0.0
    for i, p in enumerate(pts2d):
        if i:
            s_acc += math.dist(p, pts2d[i - 1])
        z = knots[-1][1]
        for (s0, z0), (s1, z1) in zip(knots, knots[1:]):
            if s_acc <= s1:
                f = 0.0 if s1 == s0 else (s_acc - s0) / (s1 - s0)
                z = z0 + f * (z1 - z0)
                break
        out.append((p[0], p[1], z))
    return out


def _arc(r, thetas_deg):
    return [
        (r * math.cos(math.radians(t)), LM_Y + r * math.sin(math.radians(t)))
        for t in thetas_deg
    ]


def _wall_x(y):
    """|x| of the vase outline at height y (flare, then chamfer)."""
    if y <= 391.709:
        return 38.113 + 0.29752 * (y - 315.947)
    return 60.654 - 1.9108 * (y - 391.709)


def _line_arc_line(p0, d0, p1, d1, r, step_mm=6.0, step_deg=6.0):
    """Dense points along: straight from p0 (heading d0) -> tangent
    fillet of radius r -> straight to p1 (arriving with heading d1).
    Both headings must be unit vectors along the travel direction."""
    x0, y0 = p0
    # corner = intersection of the two rays
    den = d0[0] * d1[1] - d0[1] * d1[0]
    t = ((p1[0] - x0) * d1[1] - (p1[1] - y0) * d1[0]) / den
    cx, cy = x0 + d0[0] * t, y0 + d0[1] * t
    cos_turn = d0[0] * d1[0] + d0[1] * d1[1]
    half = math.acos(max(-1.0, min(1.0, cos_turn))) / 2.0
    off = r * math.tan(half)
    t1 = (cx - d0[0] * off, cy - d0[1] * off)
    t2 = (cx + d1[0] * off, cy + d1[1] * off)
    cw = d0[0] * d1[1] - d0[1] * d1[0] < 0
    n0 = (d0[1], -d0[0]) if cw else (-d0[1], d0[0])
    ctr = (t1[0] + n0[0] * r, t1[1] + n0[1] * r)
    pts = []
    run = math.dist(p0, t1)
    for i in range(max(1, int(run / step_mm))):
        s = i * run / max(1, int(run / step_mm))
        pts.append((x0 + d0[0] * s, y0 + d0[1] * s))
    a0 = math.atan2(t1[1] - ctr[1], t1[0] - ctr[0])
    a1 = math.atan2(t2[1] - ctr[1], t2[0] - ctr[0])
    swp = a1 - a0
    if cw and swp > 0:
        swp -= 2 * math.pi
    if not cw and swp < 0:
        swp += 2 * math.pi
    n = max(2, int(abs(math.degrees(swp)) / step_deg))
    for i in range(n + 1):
        a = a0 + swp * i / n
        pts.append((ctr[0] + r * math.cos(a), ctr[1] + r * math.sin(a)))
    run2 = math.dist(t2, p1)
    for i in range(1, max(1, int(run2 / step_mm))):
        s = i * run2 / max(1, int(run2 / step_mm))
        pts.append((t2[0] + d1[0] * s, t2[1] + d1[1] * s))
    return pts


# The T pairs cross the bottom strip below the mains (t1f at z=3.7,
# t2f at z=9.5) -- the strip stays full-depth (18.3) in every variant
# (it carries the foot/bridge), and down there the feeders pass the
# LM/UM columns with >=7.3 (3D), which no front-half z could do. A
# short O6.8 z-step bore rises to the shared main west of the LM
# column.
TS_STEP = ((-14.0, 55.0, 3.7), (-16.8, 58.8, 11.5))  # O6.8 bore
# (both pair-channels merge into it; their caps bury inside)


def _t1_feeder():
    """T1's pair: right entry across the strip to the z-step (z=3.7)."""
    # foot lead rounds the down-the-plate corner at R~7.5 (was a sharp
    # R2.3 elbow -- caught by test_route_smoothness)
    lead = ([(13.9, 27.0), (14.0, 34.0), (13.9, 41.0), (13.2, 45.5),
             (11.5, 48.9), (8.9, 51.0)]
            if STAND_FOOT else [(13.9, 50.0)])
    # runs 1.9 past the z-step mouth so its end cap is buried inside
    # the TS_STEP bore (coincident caps poison OCC booleans)
    return lead + [(5.8, 51.9), (0.0, 51.8), (-6.0, 52.8),
                   (-10.0, 53.6), (-14.0, 55.0), (-15.8, 55.5)]


def _t2_feeder():
    """T2's pair: left entry to the same z-step (z=9.5)."""
    # T2 always runs at z=9.5 -- 5.8 of z-separation from t1f (z=3.7)
    # wherever their plans shadow or converge (coplanar near-tangent
    # pipes poison OCC booleans) -- and merges into the O6.8 step at
    # its upper half. End knots bury their caps in the step, staggered
    # from t1f's.
    if STAND_FOOT:
        return [(-14.9, 27.0), (-14.9, 48.0), (-15.2, 53.0),
                (-15.4, 56.2)]
    return [(-6.3, 51.7), (-10.0, 53.2), (-13.5, 54.8), (-15.5, 55.9)]


def _smoothstep01(value: float) -> float:
    value = max(0.0, min(1.0, float(value)))
    return value * value * (3.0 - 2.0 * value)


def _ts_captive_nudge_mm(y: float) -> float:
    """Positive-X stock/slim TS detour preserving the full D6 lumen.

    The left TS lane lies at negative X, so positive X is toward the baffle
    centreline and away from the lower-left captive land.  The short plateau
    brackets the released magnet station; both ramps have zero end slope.
    """
    if y <= TS_CAPTIVE_NUDGE_KNOTS[0][0]:
        return 0.0
    if y >= TS_CAPTIVE_NUDGE_KNOTS[-1][0]:
        return 0.0
    for (y0, x0), (y1, x1) in zip(
            TS_CAPTIVE_NUDGE_KNOTS,
            TS_CAPTIVE_NUDGE_KNOTS[1:]):
        if y <= y1:
            weight = _smoothstep01((y - y0) / (y1 - y0))
            return x0 + weight * (x1 - x0)
    raise AssertionError("unreachable V1 TS nudge interval")


def _ts_route(ts_route_key: str = TS_ROUTE_STANDARD):
    """The shared tweeter duct: left tangent+arc r=116.5 (outside the
    W22 pilot ring AND the U22 recess rim, surface-to-rim 2.9), the
    left vase flank lane, crest transition (bowed 1 mm outboard of
    the deepened 148-deg MU10 pilot), notch-corridor dive, single
    scallop pierce at (-3.3, ~430). Section per ts_section(): O6.0
    z=11.5 outside the vase, W6.6 x H4.4 oval at zc=10.45 under the
    MU10 flange seat."""
    # straight run to the arc tangent point: keep the knots SPARSE --
    # long runs of collinear spline knots degenerate OCC's pipe frame
    line = [(-16.8, 58.8), (-48.9, 88.0)]
    route = (
        line
        + _arc(116.5, [-133.99, -142, -152, -162, -172, -182, -192,
                       -202, -212])
        # The original interpolating spline bowed 0.085 mm through the
        # V1L/B2 lower-left outline between the final arc knots and the
        # waist controls.  These seven points are weighted along the
        # exact inward wall normal; they retain the established route
        # everywhere else while restoring 1.769 mm of normal wall.
        + [(-86.390863, 278.580334),
           (-71.260789, 291.898299),
           (-53.534004, 301.629510),
           (-45.665208, 305.405283),
           (-37.997095, 309.848260),
           (-34.082604, 313.202641),
           (-33.214491, 317.145618),
           (-33.3, 320.5), (-34.1, 324.0),
           (-35.3, 327.5), (-36.6, 330.8)]
        + [(-(_wall_x(y) - LANE_OFFSET), y)
           for y in (338, 346, 354, 362, 370, 378, 384)]
        + [(-53.3, 386.5), (-52.2, 389.5), (-50.2, 392.0),
           (-47.6, 393.3), (-45.0, 394.5), (-42.7, 395.7), (-40.7, 397.0)]
        + [(-38.0, 399.0), (-31.0, 402.0), (-25.6, 404.8), (-20.3, 407.5),
           (-15.5, 410.0), (-10.4, 412.8), (-5.5, 417.5), (-4.3, 420.5),
           (-3.5, 424.0), (-3.3, 427.0), (-3.3, 430.0), (-3.4, 433.0)]
    )
    if ts_route_key == TS_ROUTE_STANDARD:
        return route
    if ts_route_key == TS_ROUTE_CAPTIVE:
        return [
            (x + _ts_captive_nudge_mm(y), y)
            for x, y in route
        ]
    raise ValueError(
        f"unknown TS route key {ts_route_key!r}; choose "
        f"{TS_ROUTE_STANDARD!r} or {TS_ROUTE_CAPTIVE!r}")


# Without the stand foot the baffle bolts to the stock support via the
# four pass-throughs, and all cables must pass a D20 hole in the
# support plate: center (0, 60). Packing: LM/UM breakouts side by side
# (steep ramps crossing z=0 at (-/+5.2, 60.5)); twin O4.6 T ramps
# breaking out at (+3.8, 52.2) / (-3.1, 52.7) into the strip feeders,
# far lips up to ~1.4 past the rim (the floppy AWG24 pairs duck in).
SUPPORT_WINDOW = (0.0, 60.0, 20.0)  # cx, cy, D of the support-plate hole
T_RAMP = ((1.0, 53.4, -6.4), (6.0, 51.3, 5.0))  # right pair
T_RAMP_L = ((-1.0, 53.4, -6.4), (-6.3, 51.7, 9.5))  # left pair,
# lancing the raised t2 feeder (z=9.5); breakout ~(-3.1, 52.7)


# LM/UM entries: straight oblique ramps (p0 behind the rear face ->
# tip inside the planar main), O0.8 over their ducts.
BIG_RAMPS = {
    "lm": ((-4.6, 56.0, -6.4), (-8.0, 68.5, 12.55)),
    "um": ((2.0, 56.0, -6.4), (8.0, 60.0, 12.55)),  # 69-deg ramp
    # lancing the fan arc; breakout (4.0, 57.4) inside the D20 window
}
BIG_RAMP_D = {"lm": 9.0, "um": 8.6}
# The LM keeps its established straight rear bore.  UM is deliberately
# absent: its rear transition is part of the continuous R14 centerline
# below, not a second cylinder intersecting the planar main at 90 deg.
EXIT_RAMPS = {
    "lm": ((-10.5, 84.0, 12.55), (-10.5, 84.0, -2.0), 9.0),
}

# Profile-specific G1 UM handoff.  The quarter circle lies in the plane
# spanned by the incoming plan tangent and -Z:
#   p(phi) = start + R*sin(phi)*t + R*(1-cos(phi))*(-Z)
# so its tangent is exactly the plan tangent at phi=0 and exactly -Z at
# phi=90 deg.  R6 uses D8.2 end-to-end: 0.6 mm nominal radial slack
# around the estimated D7 cable.
UM_HANDOFF_R_MM = 14.0
UM_HANDOFF_D_MM = 8.2
UM_MAIN_D_MM = CABLE_D["um"]
UM_TRANSITION_MM = 0.0  # retained as an exported R6 design fact

UM_HANDOFF = {
    "proud": {
        "start": (46.028970, 295.354375, 12.55),
        "tangent": (-0.898794, 0.438371, 0.0),
        "outlet": (33.445854, 301.491571, -1.45),
        "rear_end": (33.445854, 301.491571, -2.00),
        "bearing_deg": 297.376,
    },
}

# V1L-only terminal-axis handoff.  The requested target is a physical
# rear-face fact, not a projection of the old rear endpoint: at z=6.8
# the R14 centerline must pass through the clean r=60 station on the
# canonical 283-degree terminal axis.  Derive every downstream point
# from those facts and the established unit tangent so a future clock,
# rear-plane, or elbow-radius change cannot leave stale magic XY values.
UM_V1L_HANDOFF_KEY = "v1l_terminal_axis"
UM_V1L_AXIS_STATION_MM = 60.0
UM_V1L_REAR_FACE_Z_MM = 6.8


def _v1l_terminal_axis_handoff():
    standard = UM_HANDOFF["proud"]
    tx, ty, _tz = standard["tangent"]
    tn = math.hypot(tx, ty)
    tx, ty = tx / tn, ty / tn

    axis = math.radians(UM_TERMINAL_CLOCK_DEG)
    rear_x = UM_CUTOUT[0] + UM_V1L_AXIS_STATION_MM * math.cos(axis)
    rear_y = UM_CUTOUT[1] + UM_V1L_AXIS_STATION_MM * math.sin(axis)

    start_z = standard["start"][2]
    # z(phi) = start_z - R * (1-cos(phi)); solve at the real V1L rear.
    cos_phi = 1.0 - ((start_z - UM_V1L_REAR_FACE_Z_MM)
                     / UM_HANDOFF_R_MM)
    if not -1.0 <= cos_phi <= 1.0:
        raise ValueError("V1L rear plane is unreachable by the R14 handoff")
    plan_to_rear = UM_HANDOFF_R_MM * math.sqrt(1.0 - cos_phi * cos_phi)
    start_x = rear_x - plan_to_rear * tx
    start_y = rear_y - plan_to_rear * ty

    outlet_x = start_x + UM_HANDOFF_R_MM * tx
    outlet_y = start_y + UM_HANDOFF_R_MM * ty
    outlet_z = start_z - UM_HANDOFF_R_MM
    bearing = math.degrees(math.atan2(outlet_y - UM_CUTOUT[1],
                                     outlet_x - UM_CUTOUT[0])) % 360.0
    return {
        "start": (start_x, start_y, start_z),
        "tangent": (tx, ty, 0.0),
        "rear_face_axis_point": (
            rear_x, rear_y, UM_V1L_REAR_FACE_Z_MM),
        "axis_station_mm": UM_V1L_AXIS_STATION_MM,
        "rear_face_bearing_deg": UM_TERMINAL_CLOCK_DEG,
        "outlet": (outlet_x, outlet_y, outlet_z),
        "rear_end": (outlet_x, outlet_y, -2.00),
        "bearing_deg": bearing,
    }


UM_HANDOFF[UM_V1L_HANDOFF_KEY] = _v1l_terminal_axis_handoff()


def _um_handoff_spec(handoff_key: str):
    try:
        return UM_HANDOFF[handoff_key]
    except KeyError as exc:
        raise ValueError(
            f"unknown UM handoff {handoff_key!r}; choose one of "
            f"{tuple(UM_HANDOFF)}"
        ) from exc


# STAND_FOOT lanes: (x, duct z, run height y_f, elbow radius, bore D).
# Four lanes persist (one per NL8 pair); the two T lanes feed the
# shared duct via the feeder/lead. Webs come from Dx alone.
FOOT_LANES = {
    "lm": (-5.45, 12.55, 10.5, 14.0, 9.0),
    "um": (5.4, 12.55, 10.5, 14.0, 8.6),
    "t1": (13.9, 3.7, 5.5, 14.0, 4.6),
    "t2": (-14.9, 9.5, 5.5, 14.0, 4.6),  # outboard: at z=9.5
    # the old x lands 7.1 from the LM lead (need 7.65)
}


def route_points(name, um_handoff_key: str = "proud",
                 ts_route_key: str = TS_ROUTE_STANDARD):
    """Planar duct centerline (z=DUCT_Z[name]) for the three routes.

    ``um_handoff_key`` changes only the terminal span of the UM route;
    ``ts_route_key`` changes only the short stock/slim lower-left captive
    keepout span.  Both defaults preserve the standard proud geometry.
    """
    if name == "t1f":
        return _with_z(_t1_feeder(), [(0, 3.7), (9999, 3.7)])
    if name == "t2f":
        return _with_z(_t2_feeder(), [(0, 9.5), (9999, 9.5)])
    if name == "lm":
        # Planar z=12.55; the line drifts from the x=-8.6 entry column
        # to x=-10.5 past the 270-deg W22 insert bore (plan-clear 3.0),
        # ending at y=85: the old y=98 tail ran UNDER the U22 flange
        # recess ring (surface 8 mm inside the rim); at y=85 the duct
        # surface clears the rim by 1.75. Straight-back exit there.
        lead = ([(-5.45, 30.0, 12.55), (-6.2, 38.0, 12.55),
                 (-7.3, 48.0, 12.55), (-7.7, 58.0, 12.55)]
                if STAND_FOOT else [])
        # knots stay SPARSE (~9 mm) -- tighter near-collinear knots
        # degenerate OCC's pipe frame (MakeSolid fails). y=84: the O9
        # exit bore (fatter than the duct) needs 1.6 to the recess rim
        return lead + [(-8.0, 68.0, 12.55), (-9.3, 76.0, 12.55),
                       (-10.5, 84.0, 12.55)]
    if name == "um":
        if ROUTING_PROFILE != "proud":
            raise RuntimeError(
                "Obi-Wan UM routing is integral core geometry; use "
                "top_baffle_nd25fw4_obiwan_route.route_cable_points()"
            )
        handoff = _um_handoff_spec(um_handoff_key)
        # O8.2 at z=12.55.  The proud route uses the R26 fan and the
        # r=119.5 U22-centered arc, then returns through the wide lower
        # neck.  Its final span is refit directly to the selected R14
        # elbow start; _um_plan_spline constrains the end tangent to the
        # analytic elbow tangent, so there is no added junction or kink.
        fan = [(30.0 + 26.0 * math.cos(math.radians(a)),
                46.1 + 26.0 * math.sin(math.radians(a)))
               for a in (180, 172, 164, 156, 148, 140, 132, 124)]
        prefix = (([(5.4, 30.0), (4.9, 37.0), (4.35, 43.0)]
                   if STAND_FOOT else [])
                  + fan + [(40.9, 84.6)])
        plan = (prefix
                + _arc(119.5, [-56.29, -44, -32, -20, -8, 4, 12, 20])
                + [(108.01, 251.03), (102.45, 258.63),
                   (95.57, 265.04), (87.60, 270.06),
                   (61.76, 283.11),
                   handoff["start"][:2]])
        return _with_z(plan, [(0, 12.55), (9999, 12.55)])
    if name == "ts":
        return [(x, y, ts_section(y)[2])
                for x, y in _ts_route(ts_route_key=ts_route_key)]
    raise ValueError(name)


def _um_plan_spline(um_handoff_key: str = "proud"):
    """Planar UM spline with an endpoint tangent constrained to the R14
    elbow.  The explicit constraint is the G1 contract; merely placing
    collinear final control points is not sufficient for a B-spline."""
    if ROUTING_PROFILE != "proud":
        raise RuntimeError("the R14 plan spline exists only in profile proud")
    spec = _um_handoff_spec(um_handoff_key)
    pts = route_points("um", um_handoff_key=um_handoff_key)
    p0, p1 = pts[0], pts[1]
    t0 = (p1[0] - p0[0], p1[1] - p0[1], p1[2] - p0[2])
    t1 = spec["tangent"]
    # Unit tangent scalars avoid OCC's default long endpoint handles,
    # which can create a tiny B-spline reversal even with the correct
    # tangent direction (observed in the no-foot proud path).
    return Spline(*pts, tangents=(t0, t1), tangent_scalars=(1.0, 1.0))


def um_handoff_points(n: int = 24, um_handoff_key: str = "proud"):
    """Analytic R14 quarter-turn plus the short rear-facing outlet run.

    The first point is the end of the planar main and the penultimate
    point is already 1.45 mm behind the nominal rear face.  Keeping the
    outlet in the returned centerline is what prevents future routing
    tests from silently excluding the hard part of the path.
    """
    if ROUTING_PROFILE != "proud":
        raise RuntimeError(
            "Obi-Wan has covered local Z bumps, not an R14 outlet handoff"
        )
    spec = _um_handoff_spec(um_handoff_key)
    sx, sy, sz = spec["start"]
    tx, ty, _tz = spec["tangent"]
    r = UM_HANDOFF_R_MM
    out = []
    for i in range(n + 1):
        phi = math.pi * 0.5 * i / n
        out.append((sx + r * math.sin(phi) * tx,
                    sy + r * math.sin(phi) * ty,
                    sz - r * (1.0 - math.cos(phi))))
    out.append(spec["rear_end"])
    return out


def um_path_wire(um_handoff_key: str = "proud"):
    """Three-edge G1 wire: constrained plan spline, R14 arc, rear line."""
    plan = _um_plan_spline(um_handoff_key=um_handoff_key)
    handoff = um_handoff_points(n=24, um_handoff_key=um_handoff_key)
    elbow = ThreePointArc(handoff[0], handoff[12], handoff[-2])
    rear = Line(handoff[-2], handoff[-1])
    return Wire([plan, elbow, rear])


def route_centerline_points(name: str, spacing_mm: float = 2.0,
                            raceway_only: bool = False,
                            um_handoff_key: str = "proud",
                            ts_route_key: str = TS_ROUTE_STANDARD):
    """Dense samples of the *complete* physical centerline.

    For Obi-Wan UM, delegate to the exact integral core route.  The former
    ``raceway_only`` external-route mode is intentionally rejected.
    Proud cutters and analytic tests use the complete R14 path.
    """
    if name == "um" and ROUTING_PROFILE == "obiwan":
        if um_handoff_key != "proud":
            raise RuntimeError(
                "um_handoff_key applies to proud-family routes, not Obi-Wan"
            )
        if raceway_only:
            raise RuntimeError("Obi-Wan has no detachable raceway")
        from top_baffle_nd25fw4_obiwan_route import route_cable_points
        return [tuple(map(float, p))
                for p in route_cable_points(spacing_mm=spacing_mm)]
    if name != "um":
        path = Spline(*route_points(name, ts_route_key=ts_route_key))
        n = max(8, int(path.length / spacing_mm))
        return [tuple(path @ (i / n)) for i in range(n + 1)]
    path = _um_plan_spline(um_handoff_key=um_handoff_key)
    n = max(20, int(path.length / spacing_mm))
    plan = [tuple(path @ (i / n)) for i in range(n + 1)]
    if raceway_only:
        raise RuntimeError("raceway_only was removed with Obi-Wan's raceway")
    return plan + um_handoff_points(
        um_handoff_key=um_handoff_key)[1:]


def _tube_loft(points, radii, sides: int = 24):
    """Ruled circular-section loft along an arbitrary 3D centerline.

    It is used instead of intersecting capped sweeps: the old UM defect
    was created precisely at such a main/bore intersection.  A single
    loft has no internal cap and also supports the Obi-Wan dipped tunnel
    cutters.
    """
    if isinstance(radii, (float, int)):
        radii = [float(radii)] * len(points)
    if len(points) != len(radii):
        raise ValueError("one radius is required per tube station")
    sections = []
    for i, (p, radius) in enumerate(zip(points, radii)):
        if i == 0:
            q0, q1 = points[0], points[1]
        elif i == len(points) - 1:
            q0, q1 = points[-2], points[-1]
        else:
            q0, q1 = points[i - 1], points[i + 1]
        tangent = tuple(q1[j] - q0[j] for j in range(3))
        tn = math.sqrt(sum(v * v for v in tangent))
        tangent = tuple(v / tn for v in tangent)
        if abs(tangent[2]) < 0.92:
            x_dir = (-tangent[1], tangent[0], 0.0)
            xn = math.hypot(x_dir[0], x_dir[1])
            x_dir = (x_dir[0] / xn, x_dir[1] / xn, 0.0)
        else:
            x_dir = (1.0, 0.0, 0.0)
        pl = Plane(origin=p, x_dir=x_dir, z_dir=tangent)
        poly = [(radius * math.cos(2 * math.pi * k / sides),
                 radius * math.sin(2 * math.pi * k / sides))
                for k in range(sides)]
        poly.append(poly[0])
        sections.append(pl * make_face(Wire(Polyline(*poly).edges())))
    return loft(sections, ruled=True)


def um_tube(raceway_only: bool = False, radial_extra_mm: float = 0.0,
            um_handoff_key: str = "proud"):
    """Proud UM bore, constant r=4.1 through its R14 handoff."""
    if ROUTING_PROFILE != "proud" or raceway_only or radial_extra_mm:
        raise RuntimeError("external Obi-Wan raceway generation was removed")
    radius = UM_HANDOFF_D_MM / 2.0 + radial_extra_mm
    path = um_path_wire(um_handoff_key=um_handoff_key)
    section = Plane(origin=path @ 0, z_dir=path % 0) * Circle(radius)
    return sweep(section, path=path)





def _ts_cutter(y_range=None, ts_route_key: str = TS_ROUTE_STANDARD):
    """The TS duct as ONE ruled loft: vertical elliptical sections
    every ~2.4 mm along the interpolating spline of the route, sized
    and positioned by ts_section(y). Outside the vase every section
    is the O6.0 circle at z=11.5, so the solid matches the old pipe
    sweep there to within the chord sag (<0.03 on the r=116.5 arc).
    ONE solid because joining coaxial tubes (round sweep + oval loft)
    leaves near-tangent sliver faces at the join -- the exposed-duct/
    open-STL-edge failure class. Sections are 24-gons (inscribed:
    bore ~1% under nominal -- wall margins stay conservative)."""
    path = Spline(*route_points("ts", ts_route_key=ts_route_key))
    n_st = max(6, int(path.length / 2.4))
    indices = list(range(n_st + 1))
    if y_range is not None:
        y_min, y_max = y_range
        in_range = [i for i in indices
                    if y_min <= float((path @ (i / n_st)).Y) <= y_max]
        if not in_range:
            raise ValueError(f"TS route does not cross y range {y_range}")
        if in_range != list(range(in_range[0], in_range[-1] + 1)):
            raise ValueError("TS route is not y-monotone in requested range")
        # Include one original ruled-loft cell beyond each requested
        # bound so the partial cutter crosses the split prism cleanly.
        i0 = max(0, in_range[0] - 1)
        i1 = min(n_st, in_range[-1] + 1)
        indices = list(range(i0, i1 + 1))
    secs = []
    for i in indices:
        t = i / n_st
        px, py, _pz = tuple(path @ t)
        tx, ty, _tz = tuple(path % t)
        nrm = math.hypot(tx, ty)
        tx, ty = tx / nrm, ty / nrm
        w2, h2, zc = ts_section(py)
        # plane y-axis = z_dir x x_dir = +Z for any plan tangent, so
        # the profile's v coordinate is GLOBAL z (C7 station idiom)
        pl = Plane(origin=(px, py, 0.0), x_dir=(-ty, tx, 0.0),
                   z_dir=(tx, ty, 0.0))
        pts = [(w2 * math.cos(a), zc + h2 * math.sin(a))
               for a in (2.0 * math.pi * k / 24.0 for k in range(24))]
        pts.append(pts[0])
        secs.append(pl * make_face(Wire(Polyline(*pts).edges())))
    return loft(secs, ruled=True)


def _entry_ramp(p0, p1, dia):
    """Straight oblique bore from outside the rear face (z<0) into the
    duct plane, along the arbitrary 3D axis p0 -> p1. Crosses z=0 at the
    rear breakout and overlaps the planar duct where it reaches z~5.5."""
    d = tuple(b - a for a, b in zip(p0, p1))
    length = math.dist(p0, p1)
    azimuth = math.degrees(math.atan2(d[1], d[0]))
    polar = math.degrees(math.acos(d[2] / length))
    mid = tuple((a + b) / 2.0 for a, b in zip(p0, p1))
    return (
        Pos(*mid)
        * Rot(Z=azimuth - 90.0)
        * Rot(X=-polar)
        * Cylinder(dia / 2.0, length)
    )


# Duct crossings of the glue seams: (x, y, z, duct r, plan extra).
# A vertical relief sphere widens each mouth laterally by the listed
# amount on both mating faces -- a funnel for the
# cross-seam fishing hand-off. Lateral only: z skins are untouched
# (the planar routing already guarantees vertical alignment). Nearest
# grown key pocket stays >=3.7 clear (seam B TS crossing binds).
SEAM_CROSSINGS = (
    (87.88, 120.0, 12.55, 3.9, 1.0),    # UM x seam A
    (-83.75, 120.0, 11.5, 3.0, 1.0),    # TS x seam A
    # The inward R6P spline crosses seam B here.  Only 0.1 mm of plan
    # funnel is needed; the old +1.0 sphere left <1 mm outer skin.
    (-33.3077, 315.95, 11.5, 3.0, 0.1),
)
SEAM_CROSSING_ROUTES = ("um", "ts", "ts")


def seam_relief_cutters(route_names=None):
    # Squashed SPHERES (plan r+extra, z-semi r-0.4): smooth everywhere,
    # so no wall/cap grazing against the bore -- flat-capped cylinders
    # left near-tangent slivers the mesher dropped (open STL edges
    # that read as an exposed duct; the c7 mid_right bug), and the
    # foot-mode spline's <0.05 lateral shift made it intermittent.
    # Poles stay inside the bore (z-semi < r); z skins untouched.
    from build123d import Sphere, scale
    selected = (set(SEAM_CROSSING_ROUTES) if route_names is None
                else set(route_names))
    return [Pos(x, y, z) * scale(Sphere(r + extra),
                                 (1.0, 1.0,
                                  (r - 0.4) / (r + extra)))
            for route, (x, y, z, r, extra)
            in zip(SEAM_CROSSING_ROUTES, SEAM_CROSSINGS)
            if route in selected]


def cable_cutters(um_handoff_key: str = "proud", route_names=None,
                  ts_y_range=None,
                  ts_route_key: str = TS_ROUTE_STANDARD):
    """Build all proud cutters, or a spatially proven route subset.

    ``route_names`` is the low-memory split/export hook.  The default
    remains byte-for-byte the complete LM/UM/TS/t1f/t2f cutter set;
    callers may select only routes that can intersect one already-known
    split region so OCC never constructs the unrelated 4,800-face TS
    loft while exporting V1L mid-right. ``ts_route_key`` preserves the
    complete section and changes only the explicitly selected centerline.
    """
    if ROUTING_PROFILE != "proud":
        raise RuntimeError(
            "Obi-Wan routing is integral to its two carrier cores; "
            "cable_cutters() is only valid for LX_ROUTING_PROFILE=proud"
        )
    all_names = {"lm", "um", "ts", "t1f", "t2f"}
    selected = all_names if route_names is None else set(route_names)
    unknown = selected - all_names
    if unknown:
        raise ValueError(f"unknown cable route(s): {sorted(unknown)}")
    cutters = []
    cutters += seam_relief_cutters(selected)
    if "lm" in selected:
        path = Spline(*route_points("lm"))
        section = Plane(origin=path @ 0, z_dir=path % 0) * Circle(
            CABLE_D["lm"] / 2.0)
        cutters.append(sweep(section, path=path))
    if "um" in selected:
        cutters.append(um_tube(um_handoff_key=um_handoff_key))
    if "ts" in selected:
        cutters.append(_ts_cutter(
            y_range=ts_y_range, ts_route_key=ts_route_key))
    # the two O3.8 pair-feeders in the strip + the z-step bore
    for fname in ("t1f", "t2f"):
        if fname not in selected:
            continue
        path = Spline(*route_points(fname))
        section = Plane(origin=path @ 0, z_dir=path % 0) * Circle(1.9)
        cutters.append(sweep(section, path=path))
    if selected & {"ts", "t1f", "t2f"}:
        cutters.append(_entry_ramp(TS_STEP[0], TS_STEP[1], 6.8))
    # The retained LM rear bore; UM is already the continuous R14 wire.
    for name, (p0, p1, dia) in EXIT_RAMPS.items():
        if name in selected:
            cutters.append(_entry_ramp(p0, p1, dia))
    if STAND_FOOT:
        # 90-deg vertical-plane elbows + runs along the foot, packed to
        # fit the 38-wide connector tongue, exiting through the channel
        # step face (z=-99, ~40 mm short of the NL8 panel). One planar
        # (constant-x) spline per route, O0.8 over its duct.
        lane_routes = {
            "lm": "lm", "um": "um", "t1": "t1f", "t2": "t2f"}
        for lane_name, (x, z_d, y_f, r, dia) in FOOT_LANES.items():
            if lane_routes[lane_name] not in selected:
                continue
            y_c, z_c = y_f + r, z_d - r
            pts = [(x, y_c + 7.5, z_d), (x, y_c + 4.0, z_d)]
            for a in range(0, 91, 15):
                pts.append((x, y_c - r * math.sin(math.radians(a)),
                            z_c + r * math.cos(math.radians(a))))
            # run the tongue, exiting through the channel step face z=-99
            for z in (z_c - 10.0, z_c - 30.0, -60.0, -85.0, -103.0):
                pts.append((x, y_f, z))
            path = Spline(*pts)
            section = Plane(origin=path @ 0, z_dir=path % 0) * Circle(dia / 2.0)
            cutters.append(sweep(section, path=path))
        return cutters
    # twin T entry ramps lancing into the O3.8 strip feeders
    if "t1f" in selected:
        cutters.append(_entry_ramp(T_RAMP[0], T_RAMP[1], 4.6))
    if "t2f" in selected:
        cutters.append(_entry_ramp(T_RAMP_L[0], T_RAMP_L[1], 4.6))
    # LM/UM entries: steep straight ramps into the D20 support window
    for name, (p0, p1) in BIG_RAMPS.items():
        if name in selected:
            cutters.append(_entry_ramp(p0, p1, BIG_RAMP_D[name]))
    return cutters
