"""Generate the current PETG-GF policy reference and delivery table."""
from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT/'src'))
from lx521_baffle.print_policy import policy, policy_sha256


def main():
    p = policy()
    machine = p['machine']
    support = p['support']
    insert = p['hardware']['M3_insert']
    retainer = p['hardware']['crescent_retainer']
    stock = p['hardware_stock']['M3_insert']
    assert stock['thread']==retainer['thread'] and stock['length_mm']==insert['insert_length_mm']
    here = ROOT/'candidates/nd25fn4_crescent'
    hardware = json.loads((here/'hardware_validation.json').read_text())
    assert hardware['status'] == 'pass'
    process = json.loads((ROOT/'captive_magnet_slicing_profile_petg_gf_06hf.json').read_text())['repo_overrides']['process']
    def disc(item):
        return f"D{item['diameter_mm']}×{item['depth_mm']} {item['grade']}"
    regular_disc = disc(p['magnets']['regular_D5'])
    crescent_disc = disc(p['magnets']['crescent_D6'])
    flush = ', '.join(f"{name} {'enabled' if support[key] == '1' else 'disabled'}" for name, key in
                     [('objects', 'flush_into_objects'), ('infill', 'flush_into_infill'), ('supports', 'flush_into_support')])
    lines = ['# PETG-GF print and hardware policies', '',
        'Generated by `scripts/generate_print_policy_docs.py` from [print_policy.json](../print_policy.json).',
        f'Policy SHA-256: `{policy_sha256()}`.', '',
        f"{machine['model']}, hardened {machine['nozzle_mm']:g} mm {machine['nozzle_variant']} nozzle; "
        f"{machine['layer_mm']:.2f} mm layers, {machine['first_layer_mm']:.2f} mm first layer. "
        f"{process['wall_loops']} walls, {process['top_shell_layers']} top layers and "
        f"{process['bottom_shell_layers']} bottom layers come from the shared Tinmorry profile. "
        'Infill percentages describe sparse regions; the slicer still makes skins and narrow regions solid.', '',
        '| Part / region | Infill | Pattern |', '|---|---:|---|']
    for role, settings in p['roles'].items():
        lines.append(f"| {role.replace('_',' ')} | {settings['sparse_infill_density']} | {settings['sparse_infill_pattern']} |")
    lines += ['', '## Materials and support', '',
        '| Material role | Material | Slicer filament | G-code tool |', '|---|---|---:|---|']
    for name in ('model','interface'):
        item = p['materials'][name]
        lines.append(f"| {name} | {item['name']} | {item['slicer_index']} | T{item['gcode_tool']} |")
    lines += ['', 'GF forms the model and support body; PLA forms the dense top contact. '
        f"{support['support_interface_top_layers']} PLA contact layers, "
        f"{support['support_top_z_distance']} mm top gap and {support['support_interface_spacing']} mm contact spacing are configured. "
        'A preview showing one selected layer is not a count of the complete interface stack. '
        'Material assignment is also checked against positive extrusion under the actual T0/T1 commands.', '',
        f"Purge is {p['materials']['purge_each_direction_mm3']:g} mm³ in each direction. Flushing: {flush}. "
        f"PLA flushing is limited to {p['materials']['interface_flush_volumetric_speed_mm3_s']:g} mm³/s, independently of PLA's printing flow limit. "
        f"Bottom contact retains {support['support_interface_bottom_layers']} layers with a "
        f"{support['support_bottom_z_distance']} mm gap and {support['support_bottom_interface_spacing']} mm spacing; it is a recorded exception, "
        'not the same finish as top contact.', '',
        'The [reported Bambu workaround](https://github.com/bambulab/BambuStudio/issues/11893#issuecomment-5575014503) '
        'concerns nozzle variant/mapping inconsistencies. Here all four per-filament maps are completed together, '
        'High Flow is pinned, and purge dimensions match the loaded filament count. Merely changing the variant '
        'fields was insufficient in our reproduction. Native export XML newlines are encoded so GUI reopening retains magnet pauses.', '',
        'The Tinmorry recipe is frozen in `vendor/TINMORRY/resolved_P2S_06HF_PETG_GF.json` and hash-checked. '
        'The GUI user preset can change without silently changing this recipe.', '',
        p['materials']['changeover_qualification']+' Actual native changeover requests are checked by `scripts/audit_changeover.py`.', '',
        '## Inserts and screws', '',
        f"The V4 now uses {retainer['screw_count']} {retainer['thread']}×{retainer['screw_length_mm']} socket-head screws, "
        f"Ø{insert['clearance_diameter_mm']:g} mm retainer clearance holes and "
        f"Ø{insert['pilot_diameter_mm']:g} mm × {insert['insert_length_mm']:g} mm "
        f"blind insert bores, matching the shared M3 bore convention. The screw circle is Ø{2*retainer['screw_circle_radius_mm']:g} mm. "
        f"The new retainer is Ø{2*retainer['retainer_outer_radius_mm']:g} mm and passes through the unchanged Ø56.4 mm cap entry. "
        f"The driver-side insert ligament is {hardware['insert_to_driver_ligament_mm']:.2f} mm; "
        f"the retainer clearance-hole edge ligament is {hardware['retainer_edge_ligament_mm']:.2f} mm. "
        'The cap, O-ring and driver seating surfaces are retained. Use the new body and retainers together; '
        'the imported M2 retention coupon is historical and does not qualify this M3 revision.', '',
        f"Use the existing **{stock['brand']} {stock['model']} — {stock['label']}** inserts: {stock['thread']} internal thread, "
        f"Ø{stock['outer_diameter_mm']:g} mm outside and {stock['length_mm']:g} mm long. "
        f"The Ø{insert['pilot_diameter_mm']:g} mm value describes our printed pilot, not the metal insert diameter. "
        f"It leaves {stock['outer_diameter_mm']-insert['pilot_diameter_mm']:.1f} mm nominal diametral interference for heat-setting. "
        'This records the established project bore convention; the supplied package drawing specifies the insert dimensions. '
        f"The {stock['length_mm']:g} mm inserts match the existing {insert['insert_length_mm']:g} mm-deep bores. "
        f"The M3×{retainer['screw_length_mm']} screw engages {hardware['screw_engagement_mm']:g} mm and stops "
        f"{hardware['insert_bottom_clearance_mm']:g} mm before the blind floor; {retainer['screw_length_mm']} mm is the screw length under its head. "
        f"The actual Ø{stock['outer_diameter_mm']:g} mm insert envelope leaves "
        f"{hardware['insert_to_driver_ligament_mm']-(stock['outer_diameter_mm']-insert['pilot_diameter_mm'])/2:.2f} mm to the V4 driver cavity. "
        f"[User-supplied package drawing](../{stock['reference_image']}).", '',
        'Regular LM M5 stepped insert bores, M3 driver/joint bores, and M2 auxiliary ties remain their own '
        'functional interfaces. Through holes and thread-forming pilots are not insert pockets. '
        'See [the insert inventory](INSERT_CATALOG.md) for those separate counts.', '',
        'There is no universal solid-infill modifier around every insert or magnet. Structural LM/UM regions '
        f"use the densities above; a {process['wall_loops']}-wall shell still applies in the "
        f"{p['roles']['crescent_tweeter_modifier']['sparse_infill_density']} tweeter region and "
        f"{p['roles']['crescent_wing']['sparse_infill_density']} wings. "
        'The no-floor bridge-root 100% modifier is retained as an explicit structural safeguard.', '',
        '## Magnets', '', '| Location | Disc | Grade | Selection |', '|---|---|---|---|']
    for item in p['magnets'].values():
        lines.append(f"| {item['use']} | Ø{item['diameter_mm']} × {item['depth_mm']} mm | {item['grade']} | {item['candidate_sku']} |")
    lines += ['', f'**The magnets are not all the same model.** The preserved LM connections remain {regular_disc}. '
        f'The crescent UM/upper-wing pairs use {crescent_disc}: four in the body and two in each selected upper wing. '
        'Do not substitute one size into the other pocket. Both are alignment/retention features with zero structural load credit.', '',
        'D5 uses the shared qualified roof/skin geometry and single-traversal toolpath checks. D6 uses inclined, '
        f"buried pockets and a swept loading-path check. The new D6 gate samples every cavity layer at ≤{p['magnets']['crescent_D6']['digital_wall_gate']['boundary_sample_mm']:g} mm "
        'boundary spacing and verifies actual model beads, width bounds and insertion timing. '
        f"In the seated-disc working region, the cavity-facing wall must have {p['magnets']['crescent_D6']['digital_wall_gate']['maximum_retaining_components']} "
        f"connected footprint and at least {100*p['magnets']['crescent_D6']['digital_wall_gate']['minimum_interlayer_overlap_fraction']:g}% "
        'footprint overlap with the prior model layer. These are digital screening criteria, not bond-strength measurements. '
        'A same-geometry crop coupon is provided separately. Digital passage does not establish physical '
        'extrusion, pause bonding, insertion or retention; those remain pending a coupon print.', '',
        '## Exceptions and blocker review', '', '| Exception | Scope | Reason / required check |', '|---|---|---|']
    for item in p['exceptions']:
        lines.append(f"| `{item['id']}` | {item['scope']} | {item['reason']} |")
    lines += ['', 'The crescent body has 12 insert sites: four UM, two LM receivers and six tweeter M3 bores. '
        'Its support exclusions follow each complete bore to the blind floor; the obsolete narrow tip cavities '
        'are gone. Cable passages and magnet loading cavities are excluded separately. Native red blocker '
        'volumes are nonprinting tools, not physical plugs.', '',
        'Remaining physical checks: insert installation, retaining-wall extrusion, magnet seating/polarity, '
        'bonding after each pause, PLA removal and cap/LM assembly fit. Acoustic performance is not qualified '
        'by mesh or slicer checks.', '',
        '## Code ownership', '',
        '| Responsibility | Authority |', '|---|---|',
        '| Material indices, mapping, purge volumes, PLA flush flow, infill roles, exceptions, V4 M3 dimensions | `print_policy.json`; `src/lx521_baffle/print_policy.py` |',
        '| Native changeover volume and flow requests | `scripts/audit_changeover.py` |',
        '| Frozen filament and complete process overrides | `captive_magnet_slicing_profile_petg_gf_06hf.json`; separate support-off wing profile |',
        '| Regular cavity geometry and qualification | `magnet_contract.py`, `magnets.py`, `gcode_analysis.py`, `artifact_emit.py` |',
        '| Regular support exclusions | `scripts/obiwan_support_blocker.py` |',
        '| V4 bore, duct and angled magnet exclusions | `candidates/nd25fn4_crescent/prepare_print.py` |',
        '| V4 caps: full ceiling coverage | `cap_support_check.py` |',
        '| D6 model-bead boundary/width gate | `scripts/captive_wall_audit.py` |',
        '| V4 insertion and internal loading relief | `print_magnets.py`, `prepare_magnet_loading.py` |',
        '| Source-bound D5 release inventory | `generate_captive_magnet_catalog.py --existing-local`; no remote rebuild claimed |',
        '| Shelf geometry/process catalog | `manage_delivery.py refresh` |', '',
        'The original [September 12 audit](../review/print_policy_audit_20260912/SUMMARY.md) remains historical. '
        'Current regeneration evidence is in `review/print_policy_update_20260912/`.', '']
    (ROOT/'docs/PRINT_POLICIES.md').write_text('\n'.join(lines))
    # The print README's quantities/time/material table is generated from
    # the delivered native slices, not copied from an older revision.
    manifest=json.loads((here/'print/manifest.json').read_text())
    by_key={r['key']:r for r in manifest['projects']}
    labels=[('body','01 — fused UM + crescent','1'),('accessories','02 — two caps and two M3 retainers','1 plate; four parts'),
            ('V4_flat_left_UPPER','Flat left upper wing','1 if flat'),('V4_flat_right_UPPER','Flat right upper wing','1 if flat'),
            ('V4_graded_left_UPPER','Graded left upper wing','1 if graded'),('V4_graded_right_UPPER','Graded right upper wing','1 if graded')]
    table=['| Plate | Print quantity | Estimated time | PETG-GF | PLA |','|---|---:|---:|---:|---:|']
    for key,label,count in labels:
        row=by_key[key];minutes=round(row['seconds']/60)
        grams={int(f['id']):f['total_used_g'] for f in row['filaments']}
        table.append(f"| [{label}]({Path(row['path']).name}) | {count} | {minutes//60} h {minutes%60:02d} min | {grams.get(1,0):.1f} g | {grams.get(2,0):.1f} g |")
    readme=here/'print/README.md';text=readme.read_text()
    start=text.index('| Plate |');end=text.index('\n\nMaterial estimates',start)
    text=text[:start]+'\n'.join(table)+text[end:]
    text=text.replace('Each tweeter exclusion also reaches its narrower blind tip.', 'All six tweeter bores now follow the shared M3 convention with a flat 4 mm blind floor; no narrow tip cavity remains.')
    import re
    text=re.sub(r'\| Upper-wing infill \| [^;]+;', '| Upper-wing infill | '+p['roles']['crescent_wing']['sparse_infill_density']+' '+p['roles']['crescent_wing']['sparse_infill_pattern']+';', text)
    text=re.sub(r'\| Purging \|[^\n]*',
        f"| Purging | {p['materials']['purge_each_direction_mm3']:g} mm³ each direction; PLA flush {p['materials']['interface_flush_volumetric_speed_mm3_s']:g} mm³/s; flushing into model, infill and supports disabled |",text)
    text=text.replace('A physical print has not yet been performed.', 'This regenerated revision has not yet been physically tested.')
    text=text.replace('use the unchanged retained geometry.', 'retain the original cap geometry and use the new M3 retainer geometry respectively.')
    text=text.replace('All 12 insert interiors, including six narrower tip reliefs, pass', 'All 12 M3 insert interiors pass')
    audit=json.loads((ROOT/by_key['body']['audit']).read_text())
    text=re.sub(r'\*\*[0-9.]+ mm outside the cable lumen\*\*', f"**{audit['ducts']['minimum_lumen_clearance_mm']:.3f} mm outside the cable lumen**",text)
    marker='## D6 qualification and shared policies'
    if marker in text: text=text[:text.index(marker)].rstrip()+'\n'
    text+='\n'+marker+'\n\n'+'''The [generated policy reference](../../../docs/PRINT_POLICIES.md) owns infill roles, material mapping and exceptions. The current body and M3 retainers are a matched revision: use six M3×8 screws with the existing Hanglife HLTI-M3-001 inserts (M3 thread, Ø5 mm outside, 4 mm long). The printed heat-set bores remain Ø4.6 × 4 mm. The cap and LM interfaces remain compatible.

Print the [D6 body/wing test pair](qualification/D6_body_wing_fit_06HF_PETG_GF_PLA.gcode.3mf) first to check the retaining skins, insertion, pause bonding and retention with your actual material and magnets. It uses the actual local pocket geometry and has its own audited pauses. [Test instructions and pending physical checks](qualification/README.md).

The new full-height D6 gate checks every cavity layer against actual model extrusion. Body and wing native jobs pass it. The D5 LM connections are retained as their own hardware family; D5×2 N52 and D6×3 N45 are not interchangeable. Auxiliary NL8 and M2 tie bores have no dedicated blockers, but fresh regular slices have been checked and contain no support in them. This remains an orientation-dependent exception.
'''
    text+=f"\n**Changeover calibration:** purge **{p['materials']['purge_each_direction_mm3']:g} mm³ each way**, with PLA flush flow **{p['materials']['interface_flush_volumetric_speed_mm3_s']:g} mm³/s**. Printing temperatures and printing flow limits retain the existing recipes. These settings are encoded in the regenerated native G-code; run the updated D6 test pair to assess actual extrusion before a full body print.\n"
    readme.write_text(text)
    print('Generated docs/PRINT_POLICIES.md')


if __name__ == '__main__': main()
