#!/usr/bin/env python3
"""Measure the exported H2C joint and write native assembly review sources."""
from pathlib import Path
import json
import sys

ROOT=Path(__file__).resolve().parents[1]
sys.path[:0]=[str(ROOT/'src'),str(ROOT/'scripts')]


def main():
    from run_memory_guarded import reexec_under_guard
    reexec_under_guard(Path(__file__))
    from build123d import import_step, Cylinder, Pos, GeomType
    from lx521_baffle.io import sha256_file
    from lx521_baffle.h2c.printing import write_json
    out=ROOT/'build/h2c';rows=[]
    def overlap(a,b):
        intersection=a&b
        return intersection.volume if intersection is not None else 0.
    for family in ('stock','slim'):
        upper=import_step(str(out/f'STEP/h2c_{family}_upper.step'))
        bmr=import_step(str(out/f'STEP/h2c_{family}_upper_bmr.step'))
        for state in ('no_floor_stand','floor_stand'):
            stems=[f'h2c_{family}_lm_no_floor_stand'] if state=='no_floor_stand' else [f'h2c_{family}_lm_lower_floor_stand',f'h2c_{family}_lm_upper_floor_stand']
            parts=[import_step(str(out/'STEP'/(s+'.step'))) for s in stems]
            for p in [*parts,upper,bmr]:
                assert p.is_valid and len(p.solids())==1 and p.volume>0
            intersections=[]
            for i,p in enumerate(parts):
                for q in [*parts[i+1:],upper,bmr]:
                    value=overlap(p,q)
                    assert value<.01,(family,state,'interference',value)
                    intersections.append(value)
            lm=parts[-1]
            sockets=[f for f in lm.faces() if f.geom_type==GeomType.CYLINDER and abs(f.radius-1.65)<1e-6
                     and abs(abs(f.axis_of_rotation.direction.Y)-1)<1e-6 and abs(f.axis_of_rotation.position.Z-9.5)<1e-6]
            pins=[f for f in upper.faces() if f.geom_type==GeomType.CYLINDER and abs(f.radius-1.5)<1e-6
                  and abs(abs(f.axis_of_rotation.direction.Y)-1)<1e-6 and abs(f.axis_of_rotation.position.Z-9.5)<1e-6]
            assert sorted(round(f.axis_of_rotation.position.X,4) for f in sockets)==[-24.,24.]
            assert sorted(round(f.axis_of_rotation.position.X,4) for f in pins)==[-24.,24.]
            # A slightly inset analytic gauge avoids coincident-boundary
            # noise while checking the complete preserved through openings.
            lm_gauge=Pos(0,200.981,0)*Cylinder(94.99,80)
            um_gauge=Pos(0,366.081,0)*Cylinder(40.99,80)
            assert all(overlap(p,lm_gauge)<.01 for p in parts)
            assert overlap(upper,um_gauge)<.01 and overlap(bmr,um_gauge)<.01
            rows.append(dict(family=family,state=state,core_pieces=len(parts)+1,
                maximum_interference_mm3=max(intersections),pin_centres_xz_mm=[[-24,9.5],[24,9.5]],
                socket_diameter_mm=3.3,pin_diameter_mm=3.,radial_clearance_mm=.15,
                axial_socket_allowance_mm=.25,joint_plane_gap_mm=.05,
                LM_gauge_diameter_mm=189.98,UM_gauge_diameter_mm=81.98,
                inputs={s:sha256_file(out/'STEP'/(s+'.step')) for s in stems+[f'h2c_{family}_upper',f'h2c_{family}_upper_bmr']}))
            files=[(s+'.step',s.replace('h2c_',''),('#8FAAB8' if i==0 else '#537B93')) for i,s in enumerate(stems)]
            files.append((f'h2c_{family}_upper.step','upper_module','#D4A759'))
            directory=out/'review_models';directory.mkdir(parents=True,exist_ok=True)
            source=directory/f'{family}_{state}.py'
            source.write_text('''"""Native H2C assembly, in the installed datum frame. Generated by verify_h2c_geometry.py."""
from pathlib import Path
from build123d import Color, Compound, Location, Part, RigidJoint, import_step
FILES = '''+repr(files)+'''
def gen_step():
    children=[]
    for filename,label,color in FILES:
        imported=import_step(str(Path(__file__).resolve().parents[1]/"STEP"/filename))
        part=Part([imported.solids()[0]]);part.label=label;part.color=Color(color)
        RigidJoint("installed_datum",part,Location((0,0,0)))
        children.append(part)
    for part in children[1:]:children[0].joints["installed_datum"].connect_to(part.joints["installed_datum"])
    return Compound(children=children,label="H2C_'''+family+'_'+state+'''")
''')
    # Use the actual native cylindrical faces as insert/fastener/straight
    # port authorities. Concave normals exclude solid registration pins.
    import numpy as np
    for step in sorted((out/'STEP').glob('h2c_*.step')):
        if not any(f'h2c_{f}_' in step.name for f in ('stock','slim')):continue
        part=import_step(str(step));bores=[]
        for face in part.faces():
            if face.geom_type!=GeomType.CYLINDER or not .5<face.radius<=4.50001:continue
            axis=face.axis_of_rotation
            direction=np.asarray(tuple(axis.direction));origin=np.asarray(tuple(axis.position))
            point=np.asarray(tuple(face.center()));normal=np.asarray(tuple(face.normal_at()))
            radial=point-origin-direction*np.dot(point-origin,direction)
            if np.dot(radial,normal)>=0:continue
            bounds=face.bounding_box();lo=np.asarray(tuple(bounds.min));hi=np.asarray(tuple(bounds.max))
            index=int(np.argmax(np.abs(direction)))
            if abs(direction[index])<.99999:continue
            start=origin.copy();end=origin.copy();start[index]=lo[index];end[index]=hi[index]
            bores.append(dict(name=f'concave_cylinder_{len(bores)+1}',radius_mm=face.radius,start=start.tolist(),end=end.tolist()))
        write_json(out/'contracts'/(step.stem+'.bores.json'),dict(step_sha256=sha256_file(step),bores=bores))
    write_json(out/'geometry_validation.json',dict(status='pass',checks=rows,
        source_sha256=sha256_file(Path(__file__)),physical_fit='pending hardware trial'))
    print('Native joint, clearances, driver gauges and assembly sources: PASS',flush=True)


if __name__=='__main__':main()
