"""Cable routing profiles for the proud family and skeletal Obi-Wan.

``LX_ROUTING_PROFILE=proud`` (R6P, the default) is the subtractive
route used by B2 and V1 and, with a keyed terminal handoff, V1L.  Its
standard UM main follows the proven outer
U22 arc, returns through the broad lower neck, and then turns through a
true R14 three-dimensional elbow to the rear outlet at (33.45, 301.49).
The old planar-main/vertical-cylinder 90 degree collision is gone: the
complete handoff is one continuous sweep.  The route is D8.2 end to end,
raising nominal radial slack around the estimated D7 cable from 0.4 to
0.6 mm.  The outlet bearing is 297.4 degrees from the MU center: still
between the lower screws, but laterally clear of the conservative 283
degree Faston pull envelope and its rear cable continuation.

V1L keeps the same upstream R6P route but refits its terminal plan span
into a second G1 R14 handoff.  The center of that bore at V1L's physical
rear plane z=6.8 is exactly 60.0 mm from the MU center on the 283-degree
terminal axis.  This exception is selected explicitly by the V1L split
builder; every other proud-family builder retains the standard outlet.

``LX_ROUTING_PROFILE=obiwan`` (R6F) selects the isolated two-carrier
platform. The LM lead uses the same R14 rear-face handoff contract as the
proud family, with a D9 terminal flare followed by a tangent free external
span. The UM
passage is printed only in LM; the shared-tweeter passage is printed only in
LM/UM. Those printed-owner spans are generated by
``top_baffle_nd25fw4_obiwan_route`` with continuous 0.8 mm minimum skins and
smooth, fully covered local Z bumps around crossed insert envelopes. UM then
floats behind its carrier and T floats behind the tweeter crescent. There is
no detachable external raceway or printed Obi-Wan grommet.

Within R6P, the LM and tweeter routes retain their established mouth datums.
The former LM planar-main/vertical-bore collision is replaced by a continuous
R14 handoff whose centerline reaches that exact rear-face datum.  The terminal
10 mm flares from D8.2 to D9 so the estimated D7.8 lead retains useful fishing
clearance through the bend.  The proud and Obi-Wan physical centerlines,
including their intentional free spans, are checked by ``test_clearances.py``
and ``test_obiwan_r6f.py`` using full-centerline curvature rather than
horizontal gaps.
"""

from __future__ import annotations

import math
import os

from build123d import (
    Bezier,
    Circle,
    Cylinder,
    Line,
    Plane,
    Polyline,
    Pos,
    Rot,
    Spline,
    ThreePointArc,
    Wire,
    loft,
    make_face,
    sweep,
)

from .geom import smoothstep01 as _smoothstep01
from .floor_bend import (
    BEND_HORIZONTAL_HANDLE_MM,
    BEND_MIN_CENTERLINE_RADIUS_MM,
    BEND_REAR_SPAN_MM,
    BEND_VERTICAL_HANDLE_MM,
    canonical_lane_controls,
    cubic_point as floor_bend_cubic_point,
)
from .base import (
    L22_CUTOUT,
    STAND_FOOT,
    UM_CUTOUT,
    UM_TERMINAL_CLOCK_DEG,
)

ROUTING_PROFILE = os.environ.get("LX_ROUTING_PROFILE", "proud").lower()
if ROUTING_PROFILE not in {"proud", "obiwan"}:
    raise ValueError(
        "LX_ROUTING_PROFILE must be 'proud' or 'obiwan', got "
        f"{ROUTING_PROFILE!r}"
    )
ROUTING_REV = {"proud": "R6P", "obiwan": "R6F"}[ROUTING_PROFILE]

LM_Y = 200.981
UM_Y = 366.081

# Duct plane depth per route -- ALL in the front half (front-datum):
# LM/UM O8.2 span z 8.45..16.65, TS 8.5..14.5 (round) /
# 8.25..12.65 (vase oval). Floors stay >=1.6 above the thin-family
# rear plane (z=6.8) except the oval's 1.45 -- the price of passing
# under the MU10 flange seat (z=14.3) with 1.65 to spare above.
DUCT_Z = {"lm": 12.55, "um": 12.55, "ts": 11.5}
LANE_OFFSET = 5.11  # TS lane center this far inside the vase wall lines

# The unified front-biased transverse-magnet plane brings the lower-left
# station into the TS duct's source-Z window in every stock/slim variant.
# Keep the complete D6 lumen and immutable magnet host by moving only this
# short span 0.60 mm toward x=0.  Exact BREP screening leaves 0.7919 mm from
# cavity void to duct and effectively zero (<0.00002 mm3) intersection with
# the helper's complete 0.60-mm-margin required land. Smoothstep ramps make
# the nudge tangent-continuous at both ends; the minimum spline bend radius
# remains >4.89 mm against the 4.5-mm release floor.
TS_ROUTE_STANDARD = "standard"
TS_ROUTE_CAPTIVE = "captive_keepout"
TS_CAPTIVE_NUDGE_MAX_MM = 0.60
TS_CAPTIVE_NUDGE_KNOTS = (
    (313.202641, 0.00),
    (317.145618, 0.30),
    (320.500000, 0.60),
    (324.000000, 0.60),
    (327.500000, 0.30),
    (330.800000, 0.00),
)

# LM carries 2 x 2.5 mm^2 (twisted ~O7.8) -> O8.2. UM carries a twisted
# 2 x 2.0 mm^2 pair (~O7.0) -> O8.2 (0.6 radial nominal slack). TS
# carries BOTH tweeter pairs side by side (~5.2 across) -> O6.0, the
# largest bore the notch corridor between the D82 rim and the vase
# chamfer admits.
CABLE_D = {"lm": 8.2, "um": 8.2, "ts": 6.0}

# Proud-family TS vase stretch: flattened oval through the thin V1/V1L
# vase corridor. W6.6 x H4.4 at zc=10.45: 1.65 under the former
# seat, 1.45 over the thin rear plane (z=6.8), and W/2=3.3 threads the
# notch corridor (>=1.84 to the D82 rim) and the vase lane (1.81 to
# the outline). The two AWG24 pairs ride side by side (~5.2 x 2.6).
# Morphs are y-parameterized (the vase path is y-monotone there):
# round O6.0 z=11.5 below y=316 and above y=425.5, full oval between
# y=330 and y=417.5, linear in the morph bands. The tube is fully
# dropped before it comes within 1.6 of the ring rim on both sides
# (rim crossings at plan dist 49.3 about (0, UM_Y): y~334 / ~415.5),
# and is round again before piercing the scallop rim (~429).
TS_OVAL = {"w2": 3.3, "h2": 2.2, "zc": 10.45,
           "y_in": (316.0, 330.0), "y_out": (417.5, 425.5)}


def _minimum_jerk01(value: float) -> float:
    """Endpoint-flat C2 quintic used by physical duct transitions."""
    value = min(1.0, max(0.0, float(value)))
    return value ** 3 * (10.0 + value * (-15.0 + 6.0 * value))


def ts_section(y):
    """(w2, h2, zc) of the TS duct section at height y: the oval drop
    under the MU10 flange seat, round O6.0 z=11.5 elsewhere. The duct
    cutter and route_points z both derive from this single law."""
    rw2, rh2, rzc = CABLE_D["ts"] / 2.0, CABLE_D["ts"] / 2.0, DUCT_Z["ts"]
    (yi0, yi1), (yo0, yo1) = TS_OVAL["y_in"], TS_OVAL["y_out"]
    ow2, oh2, ozc = TS_OVAL["w2"], TS_OVAL["h2"], TS_OVAL["zc"]
    if y <= yi0 or y >= yo1:
        return rw2, rh2, rzc
    if yi1 <= y <= yo0:
        return ow2, oh2, ozc
    if y < yi1:                       # entry morph
        f = (y - yi0) / (yi1 - yi0)
    else:                             # exit morph (f runs 1 -> 0)
        f = (yo1 - y) / (yo1 - yo0)
    # A linear morph made the centerline change slope abruptly at all four
    # section-law boundaries.  The quintic preserves the same endpoint
    # sections and the same occupied Z interval while making size and center
    # position C2 at each boundary.
    f = _minimum_jerk01(f)
    return (rw2 + f * (ow2 - rw2), rh2 + f * (oh2 - rh2),
            rzc + f * (ozc - rzc))


def _with_z(pts2d, knots):
    """Attach z to 2D route points by cumulative path length, piecewise-
    linear between (s, z) knots (the spline smooths knot corners)."""
    out, s_acc = [], 0.0
    for i, p in enumerate(pts2d):
        if i:
            s_acc += math.dist(p, pts2d[i - 1])
        z = knots[-1][1]
        for (s0, z0), (s1, z1) in zip(knots, knots[1:]):
            if s_acc <= s1:
                f = 0.0 if s1 == s0 else (s_acc - s0) / (s1 - s0)
                z = z0 + f * (z1 - z0)
                break
        out.append((p[0], p[1], z))
    return out


def _arc(r, thetas_deg):
    return [
        (r * math.cos(math.radians(t)), LM_Y + r * math.sin(math.radians(t)))
        for t in thetas_deg
    ]


def _wall_x(y):
    """|x| of the vase outline at height y (flare, then chamfer)."""
    if y <= 391.709:
        return 38.113 + 0.29752 * (y - 315.947)
    return 60.654 - 1.9108 * (y - 391.709)


def _line_arc_line(p0, d0, p1, d1, r, step_mm=6.0, step_deg=6.0):
    """Dense points along: straight from p0 (heading d0) -> tangent
    fillet of radius r -> straight to p1 (arriving with heading d1).
    Both headings must be unit vectors along the travel direction."""
    x0, y0 = p0
    # corner = intersection of the two rays
    den = d0[0] * d1[1] - d0[1] * d1[0]
    t = ((p1[0] - x0) * d1[1] - (p1[1] - y0) * d1[0]) / den
    cx, cy = x0 + d0[0] * t, y0 + d0[1] * t
    cos_turn = d0[0] * d1[0] + d0[1] * d1[1]
    half = math.acos(max(-1.0, min(1.0, cos_turn))) / 2.0
    off = r * math.tan(half)
    t1 = (cx - d0[0] * off, cy - d0[1] * off)
    t2 = (cx + d1[0] * off, cy + d1[1] * off)
    cw = d0[0] * d1[1] - d0[1] * d1[0] < 0
    n0 = (d0[1], -d0[0]) if cw else (-d0[1], d0[0])
    ctr = (t1[0] + n0[0] * r, t1[1] + n0[1] * r)
    pts = []
    run = math.dist(p0, t1)
    for i in range(max(1, int(run / step_mm))):
        s = i * run / max(1, int(run / step_mm))
        pts.append((x0 + d0[0] * s, y0 + d0[1] * s))
    a0 = math.atan2(t1[1] - ctr[1], t1[0] - ctr[0])
    a1 = math.atan2(t2[1] - ctr[1], t2[0] - ctr[0])
    swp = a1 - a0
    if cw and swp > 0:
        swp -= 2 * math.pi
    if not cw and swp < 0:
        swp += 2 * math.pi
    n = max(2, int(abs(math.degrees(swp)) / step_deg))
    for i in range(n + 1):
        a = a0 + swp * i / n
        pts.append((ctr[0] + r * math.cos(a), ctr[1] + r * math.sin(a)))
    run2 = math.dist(t2, p1)
    for i in range(1, max(1, int(run2 / step_mm))):
        s = i * run2 / max(1, int(run2 / step_mm))
        pts.append((t2[0] + d1[0] * s, t2[1] + d1[1] * s))
    return pts


# The T pairs cross the bottom strip below the mains (t1f at z=3.7,
# t2f at z=9.5) -- the strip stays full-depth (18.3) in every variant
# (it carries the foot/bridge), and down there the feeders pass the
# LM/UM columns with >=7.3 (3D), which no front-half z could do. A
# short O6.8 z-step bore rises to the shared main west of the LM
# column.
TS_STEP = ((-14.0, 55.0, 3.7), (-16.8, 58.8, 11.5))  # O6.8 bore
# (both pair-channels merge into it; their caps bury inside)


def _t1_feeder():
    """T1's pair: right entry across the strip to the z-step (z=3.7)."""
    # foot lead rounds the down-the-plate corner at R~7.5 (was a sharp
    # R2.3 elbow -- caught by test_route_smoothness)
    lead = ([(13.9, 27.0), (14.0, 34.0), (13.9, 41.0), (13.2, 45.5),
             (11.5, 48.9), (8.9, 51.0)]
            if STAND_FOOT else [(13.9, 50.0)])
    # runs 1.9 past the z-step mouth so its end cap is buried inside
    # the TS_STEP bore (coincident caps poison OCC booleans)
    return lead + [(5.8, 51.9), (0.0, 51.8), (-6.0, 52.8),
                   (-10.0, 53.6), (-14.0, 55.0), (-15.8, 55.5)]


def _t2_feeder():
    """T2's pair: left entry to the same z-step (z=9.5)."""
    # T2 always runs at z=9.5 -- 5.8 of z-separation from t1f (z=3.7)
    # wherever their plans shadow or converge (coplanar near-tangent
    # pipes poison OCC booleans) -- and merges into the O6.8 step at
    # its upper half. End knots bury their caps in the step, staggered
    # from t1f's.
    if STAND_FOOT:
        return [(-14.9, 27.0), (-14.9, 48.0), (-15.2, 53.0),
                (-15.4, 56.2)]
    return [(-6.3, 51.7), (-10.0, 53.2), (-13.5, 54.8), (-15.5, 55.9)]


def _ts_captive_nudge_mm(y: float) -> float:
    """Positive-X stock/slim TS detour preserving the full D6 lumen.

    The left TS lane lies at negative X, so positive X is toward the baffle
    centreline and away from the lower-left captive land.  The short plateau
    brackets the released magnet station; both ramps have zero end slope.
    """
    if y <= TS_CAPTIVE_NUDGE_KNOTS[0][0]:
        return 0.0
    if y >= TS_CAPTIVE_NUDGE_KNOTS[-1][0]:
        return 0.0
    for (y0, x0), (y1, x1) in zip(
            TS_CAPTIVE_NUDGE_KNOTS,
            TS_CAPTIVE_NUDGE_KNOTS[1:]):
        if y <= y1:
            weight = _smoothstep01((y - y0) / (y1 - y0))
            return x0 + weight * (x1 - x0)
    raise AssertionError("unreachable V1 TS nudge interval")


def _ts_route(ts_route_key: str = TS_ROUTE_STANDARD):
    """The shared tweeter duct: left tangent+arc r=116.5 (outside the
    W22 pilot ring AND the U22 recess rim, surface-to-rim 2.9), the
    left vase flank lane, crest transition (bowed 1 mm outboard of
    the deepened 148-deg MU10 pilot), notch-corridor dive, single
    scallop pierce at (-3.3, ~430). Section per ts_section(): O6.0
    z=11.5 outside the vase, W6.6 x H4.4 oval at zc=10.45 under the
    MU10 flange seat."""
    # straight run to the arc tangent point: keep the knots SPARSE --
    # long runs of collinear spline knots degenerate OCC's pipe frame
    line = [(-16.8, 58.8), (-48.9, 88.0)]
    route = (
        line
        + _arc(116.5, [-133.99, -142, -152, -162, -172, -182, -192,
                       -202, -212])
        # The original interpolating spline bowed 0.085 mm through the
        # V1L/B2 lower-left outline between the final arc knots and the
        # waist controls.  These seven points are weighted along the
        # exact inward wall normal; they retain the established route
        # everywhere else while restoring 1.769 mm of normal wall.
        + [(-86.390863, 278.580334),
           (-71.260789, 291.898299),
           (-53.534004, 301.629510),
           (-45.665208, 305.405283),
           (-37.997095, 309.848260),
           (-34.082604, 313.202641),
           (-33.214491, 317.145618),
           (-33.3, 320.5), (-34.1, 324.0),
           (-35.3, 327.5), (-36.6, 330.8)]
        + [(-(_wall_x(y) - LANE_OFFSET), y)
           for y in (338, 346, 354, 362, 370, 378, 384)]
        + [(-53.3, 386.5), (-52.2, 389.5), (-50.2, 392.0),
           (-47.6, 393.3), (-45.0, 394.5), (-42.7, 395.7), (-40.7, 397.0)]
        + [(-38.0, 399.0), (-31.0, 402.0), (-25.6, 404.8), (-20.3, 407.5),
           (-15.5, 410.0), (-10.4, 412.8), (-5.5, 417.5), (-4.3, 420.5),
           (-3.5, 424.0), (-3.3, 427.0), (-3.3, 430.0), (-3.4, 433.0)]
    )
    if ts_route_key == TS_ROUTE_STANDARD:
        return route
    if ts_route_key == TS_ROUTE_CAPTIVE:
        return [
            (x + _ts_captive_nudge_mm(y), y)
            for x, y in route
        ]
    raise ValueError(
        f"unknown TS route key {ts_route_key!r}; choose "
        f"{TS_ROUTE_STANDARD!r} or {TS_ROUTE_CAPTIVE!r}")


# Stock/Slim upper-vase route optimization.  The B2 flare and chamfer are
# tangent to the same UM-centred circle.  R45.91 is the balanced centerline
# between the D82 opening and both tangent exterior walls: with the W6.6 oval
# it retains at least 1.60 mm on either side.  The released route is preserved
# byte-for-byte through y=330.8, so the lower-left captive-magnet detour and
# both seam-mouth interfaces do not move.  A short G1 lead reaches the exact
# circle, and an R12 fillet turns into the unchanged final outlet position.
TS_OPTIMIZED_START_Y_MM = 330.8
TS_OPTIMIZED_LINE_JOIN_Y_MM = 346.0
TS_UM_CORRIDOR_R_MM = 45.91
TS_UM_CORRIDOR_LOWER_DXY = (-0.29752, 1.0)
TS_UM_CORRIDOR_UPPER_DXY = (1.9108, 1.0)
TS_OPTIMIZED_TRANSITION_START_HANDLE_MM = 5.0
TS_OPTIMIZED_TRANSITION_END_HANDLE_MM = 7.0
TS_OUTLET_FILLET_R_MM = 12.0
TS_OUTLET_XY_MM = (-3.4, 433.0)


def _unit_xyz(values):
    magnitude = math.sqrt(sum(float(value) ** 2 for value in values))
    if magnitude <= 1.0e-12:
        raise ValueError("zero-length routing vector")
    return tuple(float(value) / magnitude for value in values)


def _path_parameter_at_y(path, target_y: float) -> float:
    """Normalized parameter at one point on a y-monotone path."""
    if not float((path @ 0.0).Y) <= target_y <= float((path @ 1.0).Y):
        raise ValueError(f"path does not bracket y={target_y}")
    low = 0.0
    high = 1.0
    for _iteration in range(64):
        middle = (low + high) / 2.0
        if float((path @ middle).Y) < target_y:
            low = middle
        else:
            high = middle
    return (low + high) / 2.0


def _clockwise_circle_angle_for_tangent(direction_xy) -> float:
    """Circle position angle whose clockwise tangent is direction_xy."""
    dx, dy, _dz = _unit_xyz((*direction_xy, 0.0))
    return math.atan2(dx, -dy) % (2.0 * math.pi)


def _um_circle_point(radius_mm: float, angle_rad: float):
    return (
        radius_mm * math.cos(angle_rad),
        UM_Y + radius_mm * math.sin(angle_rad),
        0.0,
    )


def _tail_fillet_geometry(start, start_direction, end, end_direction,
                           radius_mm: float):
    """Tangent points and midpoint for a minor plan fillet."""
    p0 = (float(start[0]), float(start[1]))
    p1 = (float(end[0]), float(end[1]))
    d0x, d0y, _ = _unit_xyz((*start_direction[:2], 0.0))
    d1x, d1y, _ = _unit_xyz((*end_direction[:2], 0.0))
    denominator = d0x * d1y - d0y * d1x
    if abs(denominator) <= 1.0e-9:
        raise ValueError("outlet fillet tangents are parallel")
    delta_x = p1[0] - p0[0]
    delta_y = p1[1] - p0[1]
    along_start = (delta_x * d1y - delta_y * d1x) / denominator
    corner = (
        p0[0] + along_start * d0x,
        p0[1] + along_start * d0y,
    )
    turn = math.acos(max(-1.0, min(1.0, d0x * d1x + d0y * d1y)))
    offset = radius_mm * math.tan(turn / 2.0)
    first = (corner[0] - offset * d0x,
             corner[1] - offset * d0y)
    second = (corner[0] + offset * d1x,
              corner[1] + offset * d1y)
    cross = d0x * d1y - d0y * d1x
    normal = ((-d0y, d0x) if cross > 0.0 else (d0y, -d0x))
    center = (first[0] + radius_mm * normal[0],
              first[1] + radius_mm * normal[1])
    first_angle = math.atan2(first[1] - center[1],
                             first[0] - center[0])
    second_angle = math.atan2(second[1] - center[1],
                              second[0] - center[0])
    if cross > 0.0:
        sweep_angle = (second_angle - first_angle) % (2.0 * math.pi)
    else:
        sweep_angle = -((first_angle - second_angle) % (2.0 * math.pi))
    if abs(sweep_angle) >= math.pi:
        raise ValueError("outlet fillet must use the minor arc")
    middle_angle = first_angle + sweep_angle / 2.0
    middle = (
        center[0] + radius_mm * math.cos(middle_angle),
        center[1] + radius_mm * math.sin(middle_angle),
    )
    return first, middle, second


def ts_plan_path(ts_route_key: str = TS_ROUTE_STANDARD):
    """Qualified Stock/Slim shared-T plan path.

    The legacy spline owns everything through the captive-magnet span.  The
    upper-vase portion is an exact G1 line/arc/line corridor followed by an
    R12 outlet fillet, eliminating the former many-knot curvature reversals.
    """
    legacy = Spline(*[
        (x, y, 0.0) for x, y in _ts_route(ts_route_key=ts_route_key)
    ])
    start_parameter = _path_parameter_at_y(
        legacy, TS_OPTIMIZED_START_Y_MM)
    prefix = legacy.trim(0.0, start_parameter)
    prefix_end = tuple(prefix @ 1.0)
    prefix_tangent = _unit_xyz(tuple(prefix % 1.0))

    lower_direction = _unit_xyz((*TS_UM_CORRIDOR_LOWER_DXY, 0.0))
    lower_angle = _clockwise_circle_angle_for_tangent(
        TS_UM_CORRIDOR_LOWER_DXY)
    lower_tangent = _um_circle_point(TS_UM_CORRIDOR_R_MM, lower_angle)
    line_join_distance = (
        (TS_OPTIMIZED_LINE_JOIN_Y_MM - lower_tangent[1])
        / lower_direction[1]
    )
    line_join = tuple(
        lower_tangent[index] + line_join_distance * lower_direction[index]
        for index in range(3)
    )
    transition = Bezier(
        prefix_end,
        tuple(prefix_end[index]
              + TS_OPTIMIZED_TRANSITION_START_HANDLE_MM
              * prefix_tangent[index] for index in range(3)),
        tuple(line_join[index]
              - TS_OPTIMIZED_TRANSITION_END_HANDLE_MM
              * lower_direction[index] for index in range(3)),
        line_join,
    ).edge()

    upper_direction = _unit_xyz((*TS_UM_CORRIDOR_UPPER_DXY, 0.0))
    upper_angle = _clockwise_circle_angle_for_tangent(
        TS_UM_CORRIDOR_UPPER_DXY)
    upper_tangent = _um_circle_point(TS_UM_CORRIDOR_R_MM, upper_angle)
    circle_sweep = -((lower_angle - upper_angle) % (2.0 * math.pi))
    circle_mid = _um_circle_point(
        TS_UM_CORRIDOR_R_MM, lower_angle + circle_sweep / 2.0)

    legacy_outlet_tangent = _unit_xyz(tuple(legacy % 1.0))
    outlet = (*TS_OUTLET_XY_MM, 0.0)
    fillet_start, fillet_mid, fillet_end = _tail_fillet_geometry(
        upper_tangent,
        upper_direction,
        outlet,
        legacy_outlet_tangent,
        TS_OUTLET_FILLET_R_MM,
    )
    return Wire((
        prefix,
        transition,
        Line(line_join, lower_tangent).edge(),
        ThreePointArc(lower_tangent, circle_mid, upper_tangent).edge(),
        Line(upper_tangent, (*fillet_start, 0.0)).edge(),
        ThreePointArc(
            (*fillet_start, 0.0),
            (*fillet_mid, 0.0),
            (*fillet_end, 0.0),
        ).edge(),
        Line((*fillet_end, 0.0), outlet).edge(),
    ))


# Without the stand foot the baffle bolts to the stock support via the four
# rear M5 inserts, and all cables pass the support plate's D20 window.  One
# release-critical three-port datum is shared by Stock, Slim and Obi-Wan:
#
#                         LM (D9)
#                    T (D6)   UM (D8.2)
#
# Coordinates are relative to the same (0, 60) support-window centre and the
# same four bridge inserts at (+/-20, 20/70).  The unequal offsets retain at
# least 0.72 mm to the D20 rim and 0.80 mm between neighbouring lumens.  T is
# one D6 trunk carrying both AWG24 tweeter pairs; the former two-entry fan was
# both harder to identify during assembly and geometrically inconsistent with
# Obi-Wan.
SUPPORT_WINDOW = (0.0, 60.0, 20.0)  # cx, cy, D of the support-plate hole
OBIWAN_NO_FLOOR_ENTRY_WINDOW_CENTER_XY = tuple(
    map(float, SUPPORT_WINDOW[:2]))
OBIWAN_NO_FLOOR_ENTRY_WINDOW_D_MM = float(SUPPORT_WINDOW[2])
OBIWAN_NO_FLOOR_LM_ENTRY_LOCAL_XY = (-0.35, 4.76)
OBIWAN_NO_FLOOR_T_ENTRY_LOCAL_XY = (-4.75, -4.09)
OBIWAN_NO_FLOOR_UM_ENTRY_LOCAL_XY = (3.17, -4.09)


def _obiwan_no_floor_entry_xy(local_xy):
    return (
        OBIWAN_NO_FLOOR_ENTRY_WINDOW_CENTER_XY[0] + local_xy[0],
        OBIWAN_NO_FLOOR_ENTRY_WINDOW_CENTER_XY[1] + local_xy[1],
    )


OBIWAN_NO_FLOOR_LM_ENTRY_XY = _obiwan_no_floor_entry_xy(
    OBIWAN_NO_FLOOR_LM_ENTRY_LOCAL_XY)
OBIWAN_NO_FLOOR_T_ENTRY_XY = _obiwan_no_floor_entry_xy(
    OBIWAN_NO_FLOOR_T_ENTRY_LOCAL_XY)
OBIWAN_NO_FLOOR_UM_ENTRY_XY = _obiwan_no_floor_entry_xy(
    OBIWAN_NO_FLOOR_UM_ENTRY_LOCAL_XY)

# Stock/Slim intentionally alias the Obi-Wan physical interfaces.  Keep the
# aliases explicit so tests can reject any future profile-specific drift.
STOCK_SLIM_LM_ENTRY_XY = OBIWAN_NO_FLOOR_LM_ENTRY_XY
STOCK_SLIM_T_ENTRY_XY = OBIWAN_NO_FLOOR_T_ENTRY_XY
STOCK_SLIM_UM_ENTRY_XY = OBIWAN_NO_FLOOR_UM_ENTRY_XY

# Entry diameters now match the Obi-Wan ports as well as their XY datums.
# UM is D8.2 end-to-end; the deleted legacy D8.6 mouth served only the old
# oblique breakout and would consume 0.20 mm of the qualified T/UM web.
BIG_RAMP_D = {"lm": 9.0, "um": 8.2}
# One source of truth for the lower LM outlet in every family.  Its X datum
# is the established stock/slim duct X; its Y datum sits 10 mm below the
# nominal lower tangent of the D190 acoustic aperture.  Keeping this datum
# here lets the proud duct, Obi-Wan rear-normal port, and integral-floor
# continuation meet at the same physical place rather than drifting as three
# independent revisions.
LM_DUCT_OUT_X_MM = -10.5
LM_DUCT_OUT_CLEARANCE_FROM_APERTURE_MM = 10.0
LM_DUCT_OUT_Y_MM = (
    L22_CUTOUT[1] - L22_CUTOUT[2] / 2.0
    - LM_DUCT_OUT_CLEARANCE_FROM_APERTURE_MM)
# The centerline exits 2 mm behind the rear datum, matching the established
# stock/slim exit bore and allowing the floor lane to make its final R14 turn
# without opening a second slot through the lower stem.
LM_DUCT_OUT_REAR_Z_MM = -2.0

# One physical LM outlet contract for Stock, Slim and Obi-Wan.  A true R14
# centerline reaches the exact established rear-face mouth and then continues
# outside the printed part along its tangent.  Thin Slim and shallow no-floor
# carriers cannot finish a 90-degree R14 turn *inside* their rear depth; forcing
# a nominal R5--R7 quarter circle would retain an effectively sharp inner bend
# for the D7.8 cable.  Truncating the R14 at the actual face keeps the whole
# printed turn gradual while preserving the mouth center.
LM_EXIT_BEND_R_MM = 14.0
LM_EXIT_MIN_BEND_R_MM = 13.9
LM_EXIT_D_MM = 9.0
LM_EXIT_FLARE_LENGTH_MM = 10.0
LM_EXIT_STANDARD_REAR_FACE_Z_MM = 0.0
LM_EXIT_V1L_REAR_FACE_Z_MM = 6.8


# Stock/Slim no-floor entry curves.  Each cubic is tangent to its
# short external lead and to the retained main route, so the former
# straight-ramp/spline intersections cannot leave a cable-catching elbow.
# The UM joins the released fan at y=67.880790, before the nearby bridge
# insert becomes limiting; its D8.6 surface retains 1.65 mm of true 3D
# clearance from that insert.  LM uses the complete available run to its R14
# terminal handoff and therefore keeps R17.4 or better in both Stock and Slim.
STOCK_SLIM_NO_FLOOR_REAR_Z_MM = -6.4
STOCK_SLIM_NO_FLOOR_LM_CONTROL_1_MM = (
    -6.41114611, 66.28587067, 8.65591948)
STOCK_SLIM_NO_FLOOR_LM_END_HANDLE_MM = 7.95948850
STOCK_SLIM_NO_FLOOR_UM_JOIN_Y_MM = 67.88078966
STOCK_SLIM_NO_FLOOR_UM_CONTROL_1_MM = (
    5.03310110, 57.57806369, 7.77492804)
STOCK_SLIM_NO_FLOOR_UM_END_HANDLE_MM = 7.88851748

# One D6 shared-T entry carries both pairs from Obi-Wan's exact T mouth to the
# unchanged standard TS main.  The spatial cubic is G1 at the retained main,
# stays within the D20 window when back-projected to z=-6.4, and has a sampled
# minimum bend radius above R10.6.
NO_FLOOR_T_CONTROL_1_MM = (-6.22328412, 52.31152271, 6.20543104)
NO_FLOOR_T_END_HANDLE_MM = 6.69229648
NO_FLOOR_T_ENTRY_D_MM = 6.0
NO_FLOOR_T_JOIN_D_MM = 6.8
NO_FLOOR_T_JOIN_GROW_MM = 5.0
NO_FLOOR_T_CUTTER_OVERLAP_MM = 3.0

# Profile-specific G1 UM handoff.  The quarter circle lies in the plane
# spanned by the incoming plan tangent and -Z:
#   p(phi) = start + R*sin(phi)*t + R*(1-cos(phi))*(-Z)
# so its tangent is exactly the plan tangent at phi=0 and exactly -Z at
# phi=90 deg.  R6 uses D8.2 end-to-end: 0.6 mm nominal radial slack
# around the estimated D7 cable.
UM_HANDOFF_R_MM = 14.0
UM_HANDOFF_D_MM = 8.2
UM_MAIN_D_MM = CABLE_D["um"]
UM_TRANSITION_MM = 0.0  # retained as an exported R6 design fact

# Rotating the shared W22 clock to 0/60/... places one M5 receiver at
# (52.375, 291.697).  The former diagonal R14 start passed through it.  The
# replacement retains the exact old z=0 rear-face crossing and uses a
# constrained tangent corridor between the receiver and the exterior waist.
# The standard and V1L rear mouths are immutable, but their planar approach
# bearings are qualified independently.  V1L must wrap outside both the W22
# aperture and the rotated 60-degree M5 receiver before reaching its 283-degree
# physical rear-mouth station; a near-leftward approach makes that possible
# without an S-bend.
UM_STANDARD_REAR_FACE_XY_MM = (33.51352576823163, 301.4585632826594)
UM_TERMINAL_PLAN_BEARING_DEG = 184.17703583
UM_TERMINAL_PLAN_TANGENT = (
    math.cos(math.radians(UM_TERMINAL_PLAN_BEARING_DEG)),
    math.sin(math.radians(UM_TERMINAL_PLAN_BEARING_DEG)),
    0.0,
)
UM_V1L_TERMINAL_PLAN_BEARING_DEG = 180.0
UM_V1L_TERMINAL_PLAN_TANGENT = (
    math.cos(math.radians(UM_V1L_TERMINAL_PLAN_BEARING_DEG)),
    math.sin(math.radians(UM_V1L_TERMINAL_PLAN_BEARING_DEG)),
    0.0,
)
UM_V1L_PLAN_START_XY_MM = (30.8078720, 302.9999940)


def _standard_um_handoff():
    tx, ty, _tz = UM_TERMINAL_PLAN_TANGENT
    start_z = DUCT_Z["um"]
    cos_phi = 1.0 - start_z / UM_HANDOFF_R_MM
    plan_to_rear = UM_HANDOFF_R_MM * math.sqrt(1.0 - cos_phi * cos_phi)
    rear_x, rear_y = UM_STANDARD_REAR_FACE_XY_MM
    start_x = rear_x - plan_to_rear * tx
    start_y = rear_y - plan_to_rear * ty
    outlet_x = start_x + UM_HANDOFF_R_MM * tx
    outlet_y = start_y + UM_HANDOFF_R_MM * ty
    bearing = math.degrees(math.atan2(
        outlet_y - UM_CUTOUT[1], outlet_x - UM_CUTOUT[0])) % 360.0
    return {
        "start": (start_x, start_y, start_z),
        "tangent": UM_TERMINAL_PLAN_TANGENT,
        "rear_face_axis_point": (rear_x, rear_y, 0.0),
        "outlet": (outlet_x, outlet_y, start_z - UM_HANDOFF_R_MM),
        "rear_end": (outlet_x, outlet_y, -2.00),
        "bearing_deg": bearing,
    }


UM_HANDOFF = {"proud": _standard_um_handoff()}

# V1L-only terminal-axis handoff.  The requested target is a physical
# rear-face fact, not a projection of the old rear endpoint: at z=6.8
# the R14 centerline must pass through the clean r=60 station on the
# canonical 283-degree terminal axis.  Derive every downstream point
# from those facts and the established unit tangent so a future clock,
# rear-plane, or elbow-radius change cannot leave stale magic XY values.
UM_V1L_HANDOFF_KEY = "v1l_terminal_axis"
UM_V1L_AXIS_STATION_MM = 60.0
UM_V1L_REAR_FACE_Z_MM = 6.8


def _v1l_terminal_axis_handoff():
    tx, ty, _tz = UM_V1L_TERMINAL_PLAN_TANGENT
    tn = math.hypot(tx, ty)
    tx, ty = tx / tn, ty / tn

    axis = math.radians(UM_TERMINAL_CLOCK_DEG)
    rear_x = UM_CUTOUT[0] + UM_V1L_AXIS_STATION_MM * math.cos(axis)
    rear_y = UM_CUTOUT[1] + UM_V1L_AXIS_STATION_MM * math.sin(axis)

    start = (*UM_V1L_PLAN_START_XY_MM, DUCT_Z["um"])
    face = (rear_x, rear_y, UM_V1L_REAR_FACE_Z_MM)
    tangent = (tx, ty, 0.0)
    delta = tuple(face[index] - start[index] for index in range(3))
    along = sum(delta[index] * tangent[index] for index in range(3))
    normal_delta = tuple(
        delta[index] - along * tangent[index] for index in range(3)
    )
    normal_length = math.sqrt(sum(value * value for value in normal_delta))
    if along <= 0.0 or normal_length <= 0.0:
        raise ValueError("V1L circular handoff has invalid endpoint geometry")
    normal = tuple(value / normal_length for value in normal_delta)
    arc_radius = (
        along * along + normal_length * normal_length
    ) / (2.0 * normal_length)
    arc_angle = 2.0 * math.atan2(normal_length, along)

    def arc_point(phi):
        return tuple(
            start[index]
            + arc_radius * math.sin(phi) * tangent[index]
            + arc_radius * (1.0 - math.cos(phi)) * normal[index]
            for index in range(3)
        )

    face_tangent = tuple(
        math.cos(arc_angle) * tangent[index]
        + math.sin(arc_angle) * normal[index]
        for index in range(3)
    )
    if face_tangent[2] >= -1.0e-9:
        raise ValueError("V1L circular handoff does not exit through the rear")
    rear_scale = (-2.0 - face[2]) / face_tangent[2]
    rear_end = tuple(
        face[index] + rear_scale * face_tangent[index]
        for index in range(3)
    )
    outlet_scale = (-1.45 - face[2]) / face_tangent[2]
    outlet = tuple(
        face[index] + outlet_scale * face_tangent[index]
        for index in range(3)
    )
    bearing = math.degrees(math.atan2(
        outlet[1] - UM_CUTOUT[1], outlet[0] - UM_CUTOUT[0])) % 360.0
    return {
        "start": start,
        "tangent": tangent,
        "arc_mid": arc_point(arc_angle / 2.0),
        "arc_radius_mm": arc_radius,
        "arc_angle_rad": arc_angle,
        "arc_normal": normal,
        "face_tangent": face_tangent,
        "rear_face_axis_point": face,
        "axis_station_mm": UM_V1L_AXIS_STATION_MM,
        "rear_face_bearing_deg": UM_TERMINAL_CLOCK_DEG,
        "outlet": outlet,
        "rear_end": rear_end,
        "bearing_deg": bearing,
    }


UM_HANDOFF[UM_V1L_HANDOFF_KEY] = _v1l_terminal_axis_handoff()


def _um_handoff_spec(handoff_key: str):
    try:
        return UM_HANDOFF[handoff_key]
    except KeyError as exc:
        raise ValueError(
            f"unknown UM handoff {handoff_key!r}; choose one of "
            f"{tuple(UM_HANDOFF)}"
        ) from exc


def lm_exit_handoff_spec(
        planar_z_mm: float,
        rear_face_z_mm: float,
        rear_end_z_mm: float = LM_DUCT_OUT_REAR_Z_MM,
        radius_mm: float = LM_EXIT_BEND_R_MM,
        plan_bearing_deg: float = 90.0,
        face_xy_mm=None) -> dict:
    """Return the exact gradual LM rear-face handoff geometry.

    The bend begins horizontal along ``plan_bearing_deg``, follows a circular
    radius in the plane spanned by that plan tangent and -Z, reaches the
    selected mouth center on the actual rear face, then continues outside the
    print along that exact tangent.  ``face_xy_mm`` defaults to the common
    Stock/Slim/floor outlet datum; a family-specific caller may provide an
    explicitly qualified alternative without changing that shared datum.
    """
    planar_z_mm = float(planar_z_mm)
    rear_face_z_mm = float(rear_face_z_mm)
    rear_end_z_mm = float(rear_end_z_mm)
    radius_mm = float(radius_mm)
    plan_bearing_deg = float(plan_bearing_deg)
    if face_xy_mm is None:
        face_xy_mm = (LM_DUCT_OUT_X_MM, LM_DUCT_OUT_Y_MM)
    if len(face_xy_mm) != 2:
        raise ValueError("LM rear-face mouth needs one XY pair")
    face_xy_mm = tuple(map(float, face_xy_mm))
    drop = planar_z_mm - rear_face_z_mm
    if not 0.0 < drop < radius_mm:
        raise ValueError(
            "LM rear face must lie within one gradual bend radius: "
            f"drop={drop:.6f}, radius={radius_mm:.6f}")
    if rear_end_z_mm >= rear_face_z_mm:
        raise ValueError("LM external endpoint must lie behind the rear face")

    cos_phi = 1.0 - drop / radius_mm
    phi = math.acos(cos_phi)
    sin_phi = math.sin(phi)
    plan_angle = math.radians(plan_bearing_deg)
    plan_tangent = (
        math.cos(plan_angle), math.sin(plan_angle), 0.0)
    face = (
        face_xy_mm[0],
        face_xy_mm[1],
        rear_face_z_mm,
    )
    start = (
        face[0] - radius_mm * sin_phi * plan_tangent[0],
        face[1] - radius_mm * sin_phi * plan_tangent[1],
        planar_z_mm,
    )
    face_tangent = (
        cos_phi * plan_tangent[0],
        cos_phi * plan_tangent[1],
        -sin_phi,
    )
    external_length = (rear_face_z_mm - rear_end_z_mm) / sin_phi
    rear_end = tuple(
        face[index] + external_length * face_tangent[index]
        for index in range(3))
    half_phi = phi / 2.0
    arc_mid = (
        start[0] + radius_mm * math.sin(half_phi) * plan_tangent[0],
        start[1] + radius_mm * math.sin(half_phi) * plan_tangent[1],
        planar_z_mm - radius_mm * (1.0 - math.cos(half_phi)),
    )
    return {
        "radius_mm": radius_mm,
        "diameter_mm": LM_EXIT_D_MM,
        "planar_z_mm": planar_z_mm,
        "rear_face_z_mm": rear_face_z_mm,
        "rear_end_z_mm": rear_end_z_mm,
        "face_angle_rad": phi,
        "face_angle_deg_from_plan": math.degrees(phi),
        "face_angle_deg_from_rear_normal": 90.0 - math.degrees(phi),
        "plan_bearing_deg": plan_bearing_deg,
        "plan_tangent": plan_tangent,
        "start": start,
        "arc_mid": arc_mid,
        "face": face,
        "face_tangent": face_tangent,
        "rear_end": rear_end,
        "external_length_to_rear_end_mm": external_length,
    }


def lm_exit_handoff_points(
        planar_z_mm: float,
        rear_face_z_mm: float,
        n: int = 48,
        rear_end_z_mm: float = LM_DUCT_OUT_REAR_Z_MM,
        radius_mm: float = LM_EXIT_BEND_R_MM,
        plan_bearing_deg: float = 90.0,
        face_xy_mm=None):
    """Sample the analytic R14 arc plus its tangent external continuation."""
    if n < 2:
        raise ValueError("LM handoff needs at least two arc intervals")
    spec = lm_exit_handoff_spec(
        planar_z_mm, rear_face_z_mm, rear_end_z_mm, radius_mm,
        plan_bearing_deg, face_xy_mm=face_xy_mm)
    sx, sy, sz = spec["start"]
    tx, ty, _tz = spec["plan_tangent"]
    phi_face = spec["face_angle_rad"]
    out = []
    for index in range(n + 1):
        phi = phi_face * index / n
        out.append((
            sx + radius_mm * math.sin(phi) * tx,
            sy + radius_mm * math.sin(phi) * ty,
            sz - radius_mm * (1.0 - math.cos(phi)),
        ))
    arc_step_mm = radius_mm * phi_face / n
    lead_count = max(
        1,
        int(math.ceil(
            spec["external_length_to_rear_end_mm"]
            / max(arc_step_mm, 1.0e-12))),
    )
    face = spec["face"]
    rear_end = spec["rear_end"]
    for index in range(1, lead_count + 1):
        u = index / lead_count
        out.append(tuple(
            face[axis] + u * (rear_end[axis] - face[axis])
            for axis in range(3)))
    return out


def _lm_rear_face_z(um_handoff_key: str) -> float:
    _um_handoff_spec(um_handoff_key)  # validate the public selector
    return (
        LM_EXIT_V1L_REAR_FACE_Z_MM
        if um_handoff_key == UM_V1L_HANDOFF_KEY
        else LM_EXIT_STANDARD_REAR_FACE_Z_MM)


def _lm_handoff_spec(um_handoff_key: str = "proud") -> dict:
    return lm_exit_handoff_spec(
        DUCT_Z["lm"], _lm_rear_face_z(um_handoff_key))


# STAND_FOOT lanes: (x, upright z, floor y, qualified minimum bend radius,
# bore D).  Stock/Slim now use the same three-trunk physical architecture as
# Obi-Wan.  Both tweeter pairs share one D6 lane from the connector service
# cavity onward, eliminating the old two-small-bore merge in the tight lower
# corner.  X packing retains >=3.4 mm between complete neighboring bores.
FOOT_LANES = {
    "lm": (0.0, 12.55, 10.5, 41.0, 9.0),
    "um": (12.0, 12.55, 10.5, 41.0, 8.2),
    "ts": (-12.0, 11.5, 7.5, 41.0, 6.0),
}

FLOOR_ROUTE_SERVICE_START_Z_MM = -103.0
FLOOR_UM_JOIN_Y_MM = 82.0
FLOOR_UM_END_HANDLE_MM = 37.0
# Join the retained T main only after its leftward bearing is established.
# The former y=70 / 35-mm handle pulled the cubic's penultimate control back
# across the LM continuation, creating both a visible plan wiggle and a
# 5.41-mm centreline near-collision.  At y=90 with a 40-mm tangent handle the
# X controls are monotone (-12, -12, -20.92, -51.22), the entry remains G1,
# its sampled minimum radius is 57.5 mm, and the closest LM/T centrelines are
# 12.16 mm apart (3.66 mm of material between the D9 and D6 lumens).
FLOOR_TS_JOIN_Y_MM = 90.0
FLOOR_TS_END_HANDLE_MM = 40.0
FLOOR_TS_JOIN_OVERLAP_MM = 3.0


def _normalized_xyz(vector):
    length = math.sqrt(sum(float(value) ** 2 for value in vector))
    if length <= 1.0e-12:
        raise ValueError("floor-route tangent cannot be zero")
    return tuple(float(value) / length for value in vector)


def _proud_floor_join(name: str, um_handoff_key: str = "proud",
                      ts_route_key: str = TS_ROUTE_STANDARD):
    """Upper endpoint, unit tangent and cubic handle for one floor trunk."""
    if name == "lm":
        handoff = _lm_handoff_spec(um_handoff_key)
        return (
            tuple(handoff["start"]),
            tuple(handoff["plan_tangent"]),
            BEND_VERTICAL_HANDLE_MM,
        )
    if name == "um":
        path = _um_plan_spline(um_handoff_key=um_handoff_key)
        parameter = _path_parameter_at_y(path, FLOOR_UM_JOIN_Y_MM)
        return (
            tuple(path @ parameter),
            _normalized_xyz(tuple(path % parameter)),
            FLOOR_UM_END_HANDLE_MM,
        )
    if name == "ts":
        path = ts_plan_path(ts_route_key=ts_route_key)
        parameter = _path_parameter_at_y(path, FLOOR_TS_JOIN_Y_MM)
        point = path @ parameter
        return (
            (float(point.X), float(point.Y),
             ts_section(float(point.Y))[2]),
            _normalized_xyz((float((path % parameter).X),
                             float((path % parameter).Y), 0.0)),
            FLOOR_TS_END_HANDLE_MM,
        )
    raise ValueError(f"unknown proud floor trunk {name!r}")


def proud_floor_entry_controls(
        name: str, um_handoff_key: str = "proud",
        ts_route_key: str = TS_ROUTE_STANDARD):
    """Exact direct cubic from one rear foot lane to its qualified main."""
    try:
        x_mm, upright_z_mm, floor_y_mm, _radius_mm, _diameter_mm = (
            FOOT_LANES[name])
    except KeyError as exc:
        raise ValueError(f"unknown proud floor trunk {name!r}") from exc
    canonical = canonical_lane_controls(
        x_mm, floor_y_mm, upright_z_mm)
    endpoint, tangent, handle = _proud_floor_join(
        name,
        um_handoff_key=um_handoff_key,
        ts_route_key=ts_route_key,
    )
    return (
        canonical[0],
        canonical[1],
        tuple(endpoint[axis] - handle * tangent[axis]
              for axis in range(3)),
        endpoint,
    )


def proud_floor_entry_wire(
        name: str, um_handoff_key: str = "proud",
        ts_route_key: str = TS_ROUTE_STANDARD):
    """Complete round floor-route wire for LM/UM, entry-only for T."""
    controls = proud_floor_entry_controls(
        name,
        um_handoff_key=um_handoff_key,
        ts_route_key=ts_route_key,
    )
    lane = FOOT_LANES[name]
    start = (
        lane[0], lane[2], FLOOR_ROUTE_SERVICE_START_Z_MM)
    edges = [Line(start, controls[0]), Bezier(*controls)]
    if name == "lm":
        handoff = _lm_handoff_spec(um_handoff_key)
        edges.extend((
            ThreePointArc(
                handoff["start"], handoff["arc_mid"], handoff["face"]),
            Line(handoff["face"], handoff["rear_end"]),
        ))
    elif name == "um":
        main = _um_plan_spline(um_handoff_key=um_handoff_key)
        parameter = _path_parameter_at_y(main, FLOOR_UM_JOIN_Y_MM)
        edges.extend(main.trim(parameter, 1.0).edges())
        handoff = _um_handoff_spec(um_handoff_key)
        handoff_points = um_handoff_points(
            n=24, um_handoff_key=um_handoff_key)
        edges.extend((
            ThreePointArc(
                handoff_points[0],
                handoff.get("arc_mid", handoff_points[12]),
                handoff_points[-2],
            ),
            Line(handoff_points[-2], handoff_points[-1]),
        ))
    elif name == "ts":
        endpoint, tangent, _handle = _proud_floor_join(
            name, ts_route_key=ts_route_key)
        overlap_end = tuple(
            endpoint[axis] + FLOOR_TS_JOIN_OVERLAP_MM * tangent[axis]
            for axis in range(3))
        edges.append(Line(endpoint, overlap_end))
    else:
        raise ValueError(name)
    return Wire(edges)


def _proud_floor_round_cutter(
        name: str, um_handoff_key: str = "proud",
        ts_route_key: str = TS_ROUTE_STANDARD,
        radial_extra_mm: float = 0.0):
    if radial_extra_mm < 0.0:
        raise ValueError("floor-route expansion must be non-negative")
    path = proud_floor_entry_wire(
        name,
        um_handoff_key=um_handoff_key,
        ts_route_key=ts_route_key,
    )
    radius = FOOT_LANES[name][4] / 2.0 + radial_extra_mm
    section = Plane(origin=path @ 0.0, z_dir=path % 0.0) * Circle(radius)
    return sweep(section, path=path)


def proud_floor_route_facts() -> dict:
    """Dependency-light Option-B floor route contract."""
    records = {}
    for name, lane in FOOT_LANES.items():
        controls = proud_floor_entry_controls(name)
        records[name] = {
            "x_mm": lane[0],
            "upright_z_mm": lane[1],
            "floor_y_mm": lane[2],
            "diameter_mm": lane[4],
            "minimum_bend_radius_mm": lane[3],
            "service_start_z_mm": FLOOR_ROUTE_SERVICE_START_Z_MM,
            "entry_controls_xyz_mm": controls,
            "join_xyz_mm": controls[-1],
        }
    return {
        "architecture": "three_trunks_shared_D6_tweeter",
        "lane_count": len(records),
        "wall_reference_minimum_radius_mm": (
            BEND_MIN_CENTERLINE_RADIUS_MM),
        "lanes": records,
    }

# The 60-degree M5 receiver and the exterior waist leave 3.420 mm for the two
# release walls (1.8 + 1.6 mm).  Once the receiver and D8.2 duct radii are
# removed, only 0.020 mm remains.  Do not interpolate freely across it.  The
# route below touches one exact straight tangent through that corridor, with
# 1.810 mm to the M5 receiver and 1.610 mm to the exterior at the limiting
# station.  Cubics on either side are G1 and have monotone signed curvature.
UM_OUTER_ARC_ANGLES_DEG = (
    -56.29, -44.0, -32.0, -20.0, -8.0, 4.0, 12.0, 20.0,
    26.8, 33.6, 36.0,
)
UM_V1L_OUTER_ARC_ANGLES_DEG = (
    -56.29, -44.0, -32.0, -20.0, -8.0, 4.0, 12.0, 20.0,
    26.8, 33.6, 36.0,
)
UM_FAIR_TAIL_REVIEW_ANCHOR_XY = tuple(_arc(
    119.5, [UM_V1L_OUTER_ARC_ANGLES_DEG[-1]])[0])
# Public routing-diagram datums.  Keep the keyed mapping because review tools
# select the alternate V1L tail by handoff key rather than duplicating a
# coordinate that can drift when the qualified prefix changes.
UM_FAIR_TAIL_GUIDE_XY = {
    "proud": tuple(_arc(119.5, [UM_OUTER_ARC_ANGLES_DEG[-1]])[0]),
    UM_V1L_HANDOFF_KEY: UM_FAIR_TAIL_REVIEW_ANCHOR_XY,
}
UM_FAIR_TAIL_REVIEW_START_Y_MM = 238.0
UM_W22_BYPASS_CONTACT_XY_MM = (56.62314617, 299.81242889)
UM_W22_BYPASS_TANGENT_XY = (-0.88595304, 0.46377496)
UM_W22_BYPASS_ENTRY_LEAD_MM = 16.0
UM_W22_BYPASS_ENTRY_START_HANDLE_MM = 14.0
UM_W22_BYPASS_ENTRY_END_HANDLE_MM = 14.0
UM_W22_BYPASS_TERMINAL_PARAMETERS = {
    "proud": {
        "lead_mm": 2.51445747,
        "start_handle_mm": 1.11810767,
        "end_handle_mm": 3.52681911,
    },
    UM_V1L_HANDOFF_KEY: {
        "lead_mm": 0.0,
        "start_handle_mm": 6.8,
        "end_handle_mm": 8.0,
    },
}


def _um_prefix_points(arc_angles=UM_OUTER_ARC_ANGLES_DEG):
    """Released UM prefix through the qualified R119.5 review anchor."""
    fan = [(30.0 + 26.0 * math.cos(math.radians(angle)),
            46.1 + 26.0 * math.sin(math.radians(angle)))
           for angle in (180, 172, 164, 156, 148, 140, 132, 124)]
    return (
        ([(5.4, 30.0), (4.9, 37.0), (4.35, 43.0)]
         if STAND_FOOT else [])
        + fan
        + [(40.9, 84.6)]
        + _arc(119.5, arc_angles)
    )


def route_points(name, um_handoff_key: str = "proud",
                 ts_route_key: str = TS_ROUTE_STANDARD):
    """Planar duct centerline (z=DUCT_Z[name]) for the three routes.

    ``um_handoff_key`` changes only the terminal span of the UM route;
    ``ts_route_key`` changes only the short stock/slim lower-left captive
    keepout span.  Both defaults preserve the standard proud geometry.
    """
    if name == "t1f":
        return _with_z(_t1_feeder(), [(0, 3.7), (9999, 3.7)])
    if name == "t2f":
        return _with_z(_t2_feeder(), [(0, 9.5), (9999, 9.5)])
    if name == "lm":
        # Planar z=12.55; the line drifts from the x=-8.6 entry column
        # to the analytic R14 start through the lower W22 insert sector.  The
        # handoff itself reaches the shared lower rear-face mouth exactly
        # 10 mm outside the D190 acoustic aperture; it is not represented by
        # a perpendicular cylinder colliding with this planar spline.
        handoff = _lm_handoff_spec(um_handoff_key)
        lead = ([(-5.45, 30.0, 12.55), (-6.2, 38.0, 12.55),
                 (-7.3, 48.0, 12.55), (-7.7, 58.0, 12.55)]
                if STAND_FOOT else [])
        # Knots stay sparse (~9 mm); tighter near-collinear knots degenerate
        # OCC's pipe frame (MakeSolid fails).
        return lead + [(-8.0, 68.0, 12.55), (-9.9, 76.0, 12.55),
                       handoff["start"]]
    if name == "um":
        if ROUTING_PROFILE != "proud":
            raise RuntimeError(
                "Obi-Wan UM routing is integral core geometry; use "
                "top_baffle_nd25fw4_obiwan_route.route_cable_points()"
            )
        path = _um_plan_spline(um_handoff_key=um_handoff_key)
        count = max(32, int(math.ceil(float(path.length) / 6.0)))
        return [tuple(path @ (index / count))
                for index in range(count + 1)]
    if name == "ts":
        path = ts_plan_path(ts_route_key=ts_route_key)
        count = max(32, int(math.ceil(float(path.length) / 6.0)))
        points = []
        for index in range(count + 1):
            point = path @ (index / count)
            points.append((
                float(point.X),
                float(point.Y),
                ts_section(float(point.Y))[2],
            ))
        return points
    raise ValueError(name)


def _um_plan_spline(um_handoff_key: str = "proud"):
    """Planar UM wire constrained through the narrow rotated-M5 corridor.

    The name is retained for public compatibility.  The result is now a
    multi-edge G1 wire instead of one free interpolating spline: prefix,
    entry cubic, exact tangent line, and terminal cubic.
    """
    if ROUTING_PROFILE != "proud":
        raise RuntimeError("the R14 plan spline exists only in profile proud")
    spec = _um_handoff_spec(um_handoff_key)
    arc_angles = (
        UM_V1L_OUTER_ARC_ANGLES_DEG
        if um_handoff_key == UM_V1L_HANDOFF_KEY
        else UM_OUTER_ARC_ANGLES_DEG)
    prefix_points = [(*point, DUCT_Z["um"])
                     for point in _um_prefix_points(arc_angles)]
    p0, p1 = prefix_points[0], prefix_points[1]
    t0 = (p1[0] - p0[0], p1[1] - p0[1], p1[2] - p0[2])
    arc_angle = math.radians(arc_angles[-1])
    arc_tangent = (-math.sin(arc_angle), math.cos(arc_angle), 0.0)
    prefix = Spline(
        *prefix_points,
        tangents=(t0, arc_tangent),
        tangent_scalars=(1.0, 1.0),
    )

    tangent = (*UM_W22_BYPASS_TANGENT_XY, 0.0)
    contact = (*UM_W22_BYPASS_CONTACT_XY_MM, DUCT_Z["um"])
    entry = tuple(
        contact[index] - UM_W22_BYPASS_ENTRY_LEAD_MM * tangent[index]
        for index in range(3))
    prefix_end = tuple(prefix @ 1.0)
    entry_curve = Bezier(
        prefix_end,
        tuple(prefix_end[index]
              + UM_W22_BYPASS_ENTRY_START_HANDLE_MM * arc_tangent[index]
              for index in range(3)),
        tuple(entry[index]
              - UM_W22_BYPASS_ENTRY_END_HANDLE_MM * tangent[index]
              for index in range(3)),
        entry,
    ).edge()

    parameters = UM_W22_BYPASS_TERMINAL_PARAMETERS[um_handoff_key]
    terminal_start = tuple(
        contact[index] + parameters["lead_mm"] * tangent[index]
        for index in range(3))
    terminal_end = tuple(spec["start"])
    terminal_tangent = tuple(spec["tangent"])
    terminal_curve = Bezier(
        terminal_start,
        tuple(terminal_start[index]
              + parameters["start_handle_mm"] * tangent[index]
              for index in range(3)),
        tuple(terminal_end[index]
              - parameters["end_handle_mm"] * terminal_tangent[index]
              for index in range(3)),
        terminal_end,
    ).edge()
    return Wire((
        prefix,
        entry_curve,
        Line(entry, terminal_start).edge(),
        terminal_curve,
    ))


def _lm_plan_spline(um_handoff_key: str = "proud"):
    """Planar LM spline constrained G1 into its shared R14 handoff."""
    if ROUTING_PROFILE != "proud":
        raise RuntimeError("the proud LM plan spline requires profile proud")
    pts = route_points("lm", um_handoff_key=um_handoff_key)
    p0, p1 = pts[0], pts[1]
    t0 = tuple(p1[index] - p0[index] for index in range(3))
    return Spline(
        *pts,
        tangents=(t0, (0.0, 1.0, 0.0)),
        tangent_scalars=(1.0, 1.0),
    )


def _external_point_on_tangent(face, inner_control, rear_z_mm: float):
    """Continue a face tangent to one exact external rear-Z station."""
    face = tuple(map(float, face))
    inner_control = tuple(map(float, inner_control))
    direction = tuple(
        inner_control[index] - face[index] for index in range(3))
    if direction[2] <= 1.0e-9:
        raise ValueError("entry tangent must point into positive Z")
    scale = (face[2] - float(rear_z_mm)) / direction[2]
    return tuple(
        face[index] - scale * direction[index] for index in range(3))


def _sample_path_points(path, spacing_mm: float = 1.25):
    """Arc-length-like samples including both exact path endpoints."""
    count = max(8, int(math.ceil(float(path.length) / spacing_mm)))
    return [tuple(path @ (index / count)) for index in range(count + 1)]


def stock_slim_no_floor_entry_path(
        name: str, um_handoff_key: str = "proud"):
    """Continuous rear-entry path for one Stock/Slim no-floor duct.

    The returned wire begins at z=-6.4, crosses the immutable released mouth
    at z=0, and terminates G1 on the retained LM or UM route.  It deliberately
    does not replace either upper terminal handoff.
    """
    if name == "lm":
        mouth = (*STOCK_SLIM_LM_ENTRY_XY, 0.0)
        control_1 = STOCK_SLIM_NO_FLOOR_LM_CONTROL_1_MM
        endpoint = _lm_handoff_spec(um_handoff_key)["start"]
        control_2 = (
            endpoint[0],
            endpoint[1] - STOCK_SLIM_NO_FLOOR_LM_END_HANDLE_MM,
            endpoint[2],
        )
        continuation = []
    elif name == "um":
        mouth = (*STOCK_SLIM_UM_ENTRY_XY, 0.0)
        control_1 = STOCK_SLIM_NO_FLOOR_UM_CONTROL_1_MM
        main = _um_plan_spline(um_handoff_key=um_handoff_key)
        join_parameter = _path_parameter_at_y(
            main, STOCK_SLIM_NO_FLOOR_UM_JOIN_Y_MM)
        endpoint = tuple(main @ join_parameter)
        tangent = _unit_xyz(tuple(main % join_parameter))
        control_2 = tuple(
            endpoint[index]
            - STOCK_SLIM_NO_FLOOR_UM_END_HANDLE_MM * tangent[index]
            for index in range(3)
        )
        # ``main`` is a multi-edge G1 wire after the rotated-M5 reroute.
        # Flatten the trimmed continuation back to edges before constructing
        # the entry wire; nesting a Wire inside Wire is not a valid OCC wire.
        continuation = list(main.trim(join_parameter, 1.0).edges())
    else:
        raise ValueError("no-floor entry name must be 'lm' or 'um'")

    external = _external_point_on_tangent(
        mouth, control_1, STOCK_SLIM_NO_FLOOR_REAR_Z_MM)
    return Wire((
        Line(external, mouth).edge(),
        Bezier(mouth, control_1, control_2, endpoint).edge(),
        *continuation,
    ))


def no_floor_t_entry_path():
    """Return the single shared-T entry from the rear mouth to the TS main."""
    if STAND_FOOT:
        raise RuntimeError("the D20 T entry exists only without the foot")
    mouth = (*STOCK_SLIM_T_ENTRY_XY, 0.0)
    endpoint_point = ts_plan_path(TS_ROUTE_STANDARD) @ 0.0
    endpoint = (
        float(endpoint_point.X),
        float(endpoint_point.Y),
        ts_section(float(endpoint_point.Y))[2],
    )
    tangent_vector = ts_plan_path(TS_ROUTE_STANDARD) % 0.0
    tangent = _unit_xyz((
        float(tangent_vector.X), float(tangent_vector.Y), 0.0))
    control_2 = tuple(
        endpoint[index] - NO_FLOOR_T_END_HANDLE_MM * tangent[index]
        for index in range(3)
    )
    external = _external_point_on_tangent(
        mouth, NO_FLOOR_T_CONTROL_1_MM,
        STOCK_SLIM_NO_FLOOR_REAR_Z_MM)
    return Wire((
        Line(external, mouth).edge(),
        Bezier(
            mouth,
            NO_FLOOR_T_CONTROL_1_MM,
            control_2,
            endpoint,
        ).edge(),
    ))


def lm_handoff_points(n: int = 48, um_handoff_key: str = "proud"):
    """Analytic R14 LM bend through the physical rear-face mouth."""
    return lm_exit_handoff_points(
        DUCT_Z["lm"], _lm_rear_face_z(um_handoff_key), n=n)


def lm_path_wire(um_handoff_key: str = "proud"):
    """Three-edge G1 LM wire: constrained plan, R14 arc, tangent lead."""
    plan = _lm_plan_spline(um_handoff_key=um_handoff_key)
    spec = _lm_handoff_spec(um_handoff_key)
    elbow = ThreePointArc(spec["start"], spec["arc_mid"], spec["face"])
    rear = Line(spec["face"], spec["rear_end"])
    return Wire([plan, elbow, rear])


def um_handoff_points(n: int = 24, um_handoff_key: str = "proud"):
    """Analytic circular turn plus the short rear-facing outlet run.

    The first point is the end of the planar main and the penultimate
    point is already 1.45 mm behind the nominal rear face.  Keeping the
    outlet in the returned centerline is what prevents future routing
    tests from silently excluding the hard part of the path.
    """
    if ROUTING_PROFILE != "proud":
        raise RuntimeError(
            "Obi-Wan has covered local Z bumps, not an R14 outlet handoff"
        )
    spec = _um_handoff_spec(um_handoff_key)
    sx, sy, sz = spec["start"]
    tx, ty, _tz = spec["tangent"]
    if um_handoff_key == UM_V1L_HANDOFF_KEY:
        r = spec["arc_radius_mm"]
        phi_total = spec["arc_angle_rad"]
        nx, ny, nz = spec["arc_normal"]
    else:
        r = UM_HANDOFF_R_MM
        phi_total = math.pi * 0.5
        nx, ny, nz = (0.0, 0.0, -1.0)
    out = []
    for i in range(n + 1):
        phi = phi_total * i / n
        out.append((sx + r * math.sin(phi) * tx
                    + r * (1.0 - math.cos(phi)) * nx,
                    sy + r * math.sin(phi) * ty
                    + r * (1.0 - math.cos(phi)) * ny,
                    sz + r * (1.0 - math.cos(phi)) * nz))
    out.append(spec["rear_end"])
    return out


def um_path_wire(um_handoff_key: str = "proud"):
    """G1 wire: constrained plan, circular handoff, and rear lead."""
    plan = _um_plan_spline(um_handoff_key=um_handoff_key)
    spec = _um_handoff_spec(um_handoff_key)
    handoff = um_handoff_points(n=24, um_handoff_key=um_handoff_key)
    elbow = ThreePointArc(
        handoff[0],
        spec.get("arc_mid", handoff[12]),
        handoff[-2],
    )
    rear = Line(handoff[-2], handoff[-1])
    return Wire([*plan.edges(), elbow, rear])


def route_centerline_points(name: str, spacing_mm: float = 2.0,
                            raceway_only: bool = False,
                            um_handoff_key: str = "proud",
                            ts_route_key: str = TS_ROUTE_STANDARD):
    """Dense samples of the *complete* physical centerline.

    For Obi-Wan UM, delegate to the exact integral core route.  The former
    ``raceway_only`` external-route mode is intentionally rejected.
    Proud cutters and analytic tests use the complete R14 path.
    """
    if name == "um" and ROUTING_PROFILE == "obiwan":
        if um_handoff_key != "proud":
            raise RuntimeError(
                "um_handoff_key applies to proud-family routes, not Obi-Wan"
            )
        if raceway_only:
            raise RuntimeError("Obi-Wan has no detachable raceway")
        from .obiwan.route import route_cable_points
        return [tuple(map(float, p))
                for p in route_cable_points(spacing_mm=spacing_mm)]
    if STAND_FOOT and ROUTING_PROFILE == "proud":
        if raceway_only:
            raise RuntimeError("floor routes have no detachable raceway")
        if name in {"lm", "um"}:
            return _sample_path_points(
                proud_floor_entry_wire(
                    name,
                    um_handoff_key=um_handoff_key,
                    ts_route_key=ts_route_key,
                ),
                spacing_mm=spacing_mm,
            )
        if name == "ts":
            controls = proud_floor_entry_controls(
                "ts", ts_route_key=ts_route_key)
            line_start = (
                FOOT_LANES["ts"][0],
                FOOT_LANES["ts"][2],
                FLOOR_ROUTE_SERVICE_START_Z_MM,
            )
            line_count = max(
                2, int(math.ceil(
                    math.dist(line_start, controls[0]) / spacing_mm)))
            points = [tuple(
                line_start[axis]
                + index / line_count
                * (controls[0][axis] - line_start[axis])
                for axis in range(3))
                for index in range(line_count + 1)]
            cubic_length = float(Bezier(*controls).length)
            cubic_count = max(
                8, int(math.ceil(cubic_length / spacing_mm)))
            points.extend(
                floor_bend_cubic_point(controls, index / cubic_count)
                for index in range(1, cubic_count + 1))

            main = ts_plan_path(ts_route_key=ts_route_key)
            join_parameter = _path_parameter_at_y(
                main, FLOOR_TS_JOIN_Y_MM)
            upper_length = float(main.length) * (1.0 - join_parameter)
            upper_count = max(
                16, int(math.ceil(upper_length / spacing_mm)))
            for index in range(1, upper_count + 1):
                parameter = (
                    join_parameter
                    + (1.0 - join_parameter) * index / upper_count)
                point = main @ parameter
                points.append((
                    float(point.X),
                    float(point.Y),
                    ts_section(float(point.Y))[2],
                ))
            return points
    if name == "lm":
        path = _lm_plan_spline(um_handoff_key=um_handoff_key)
        n = max(12, int(path.length / spacing_mm))
        plan = [tuple(path @ (i / n)) for i in range(n + 1)]
        return plan + lm_handoff_points(
            n=max(12, int(LM_EXIT_BEND_R_MM / spacing_mm)),
            um_handoff_key=um_handoff_key)[1:]
    if name == "ts":
        path = ts_plan_path(ts_route_key=ts_route_key)
        count = max(16, int(math.ceil(float(path.length) / spacing_mm)))
        points = []
        for index in range(count + 1):
            point = path @ (index / count)
            points.append((
                float(point.X),
                float(point.Y),
                ts_section(float(point.Y))[2],
            ))
        return points
    if name != "um":
        path = Spline(*route_points(name, ts_route_key=ts_route_key))
        n = max(8, int(path.length / spacing_mm))
        return [tuple(path @ (i / n)) for i in range(n + 1)]
    path = _um_plan_spline(um_handoff_key=um_handoff_key)
    n = max(20, int(path.length / spacing_mm))
    plan = [tuple(path @ (i / n)) for i in range(n + 1)]
    if raceway_only:
        raise RuntimeError("raceway_only was removed with Obi-Wan's raceway")
    return plan + um_handoff_points(
        um_handoff_key=um_handoff_key)[1:]


def _tube_loft(points, radii, sides: int = 24):
    """Ruled circular-section loft along an arbitrary 3D centerline.

    It is used instead of intersecting capped sweeps: the old UM defect
    was created precisely at such a main/bore intersection.  A single
    loft has no internal cap and also supports the Obi-Wan dipped tunnel
    cutters.
    """
    if isinstance(radii, (float, int)):
        radii = [float(radii)] * len(points)
    if len(points) != len(radii):
        raise ValueError("one radius is required per tube station")
    sections = []
    for i, (p, radius) in enumerate(zip(points, radii)):
        if i == 0:
            q0, q1 = points[0], points[1]
        elif i == len(points) - 1:
            q0, q1 = points[-2], points[-1]
        else:
            q0, q1 = points[i - 1], points[i + 1]
        tangent = tuple(q1[j] - q0[j] for j in range(3))
        tn = math.sqrt(sum(v * v for v in tangent))
        tangent = tuple(v / tn for v in tangent)
        if abs(tangent[2]) < 0.92:
            x_dir = (-tangent[1], tangent[0], 0.0)
            xn = math.hypot(x_dir[0], x_dir[1])
            x_dir = (x_dir[0] / xn, x_dir[1] / xn, 0.0)
        else:
            x_dir = (1.0, 0.0, 0.0)
        pl = Plane(origin=p, x_dir=x_dir, z_dir=tangent)
        poly = [(radius * math.cos(2 * math.pi * k / sides),
                 radius * math.sin(2 * math.pi * k / sides))
                for k in range(sides)]
        poly.append(poly[0])
        sections.append(pl * make_face(Wire(Polyline(*poly).edges())))
    return loft(sections, ruled=True)


def _cumulative_distances(points):
    distances = [0.0]
    for first, second in zip(points[:-1], points[1:]):
        distances.append(distances[-1] + math.dist(first, second))
    return distances


def _stock_slim_no_floor_um_sections(
        um_handoff_key: str = "proud", radial_extra_mm: float = 0.0):
    path = stock_slim_no_floor_entry_path(
        "um", um_handoff_key=um_handoff_key)
    points = _sample_path_points(path)
    distances = _cumulative_distances(points)
    mouth_distance = math.dist(points[0], (*STOCK_SLIM_UM_ENTRY_XY, 0.0))
    radii = []
    for distance in distances:
        u = min(1.0, max(
            0.0, (distance - mouth_distance) / 8.0))
        taper = _smoothstep01(u)
        radii.append(
            BIG_RAMP_D["um"] / 2.0
            + (UM_HANDOFF_D_MM / 2.0 - BIG_RAMP_D["um"] / 2.0)
            * taper
            + radial_extra_mm
        )
    handoff = um_handoff_points(
        um_handoff_key=um_handoff_key)
    points.extend(handoff[1:])
    radii.extend([
        UM_HANDOFF_D_MM / 2.0 + radial_extra_mm
    ] * (len(handoff) - 1))
    return points, radii


def _stock_slim_no_floor_lm_sections(
        um_handoff_key: str = "proud", radial_extra_mm: float = 0.0):
    path = stock_slim_no_floor_entry_path(
        "lm", um_handoff_key=um_handoff_key)
    points = _sample_path_points(path)
    distances = _cumulative_distances(points)
    mouth_distance = math.dist(points[0], (*STOCK_SLIM_LM_ENTRY_XY, 0.0))
    flare_start = max(0.0, distances[-1] - LM_EXIT_FLARE_LENGTH_MM)
    base_radius = CABLE_D["lm"] / 2.0
    exit_radius = LM_EXIT_D_MM / 2.0
    radii = []
    for distance in distances:
        entry_u = min(1.0, max(
            0.0, (distance - mouth_distance) / 8.0))
        entry_radius = (
            exit_radius
            + (base_radius - exit_radius) * _smoothstep01(entry_u)
        )
        flare_u = min(1.0, max(
            0.0,
            (distance - flare_start)
            / max(LM_EXIT_FLARE_LENGTH_MM, 1.0e-12),
        ))
        flare_radius = (
            base_radius
            + (exit_radius - base_radius) * _smoothstep01(flare_u)
        )
        radii.append(max(entry_radius, flare_radius) + radial_extra_mm)
    handoff = lm_handoff_points(
        n=32, um_handoff_key=um_handoff_key)
    points.extend(handoff[1:])
    radii.extend([
        exit_radius + radial_extra_mm
    ] * (len(handoff) - 1))
    return points, radii


def _no_floor_t_entry_sections(radial_extra_mm: float = 0.0):
    """Sample the D6 entry, smooth D6.8 buried join, and TS overlap."""
    if STAND_FOOT:
        raise RuntimeError("the D20 T entry exists only without the foot")
    if radial_extra_mm < 0.0:
        raise ValueError("T entry expansion must be non-negative")
    points = _sample_path_points(no_floor_t_entry_path(), spacing_mm=0.9)
    physical_end_distance = _cumulative_distances(points)[-1]
    # Continue through the exact shared-T interface by 3 mm.  The physical
    # path contract still ends at (-16.8, 58.8, 11.5); this cutter-only lead
    # buries both caps so the host subtraction cannot retain a zero-area
    # triangulation face at that otherwise coincident section.
    ts_path = ts_plan_path(TS_ROUTE_STANDARD)
    overlap_count = max(2, int(math.ceil(
        NO_FLOOR_T_CUTTER_OVERLAP_MM / 0.9)))
    overlap_parameter = min(
        1.0, NO_FLOOR_T_CUTTER_OVERLAP_MM / float(ts_path.length))
    for index in range(1, overlap_count + 1):
        point = ts_path @ (overlap_parameter * index / overlap_count)
        points.append((
            float(point.X),
            float(point.Y),
            ts_section(float(point.Y))[2],
        ))
    distances = _cumulative_distances(points)
    entry_radius = NO_FLOOR_T_ENTRY_D_MM / 2.0
    join_radius = NO_FLOOR_T_JOIN_D_MM / 2.0
    radii = []
    for distance in distances:
        grow_u = min(1.0, max(
            0.0,
            (distance - (physical_end_distance - NO_FLOOR_T_JOIN_GROW_MM))
            / NO_FLOOR_T_JOIN_GROW_MM,
        ))
        radii.append(
            entry_radius
            + (join_radius - entry_radius) * _smoothstep01(grow_u)
            + radial_extra_mm)
    return points, radii


def no_floor_t_entry_cutter(radial_extra_mm: float = 0.0):
    """Continuous no-floor T entry with an enlarged buried TS join."""
    points, radii = _no_floor_t_entry_sections(radial_extra_mm)
    return _tube_loft(
        points, radii, sides=24,
    )


def um_tube(raceway_only: bool = False, radial_extra_mm: float = 0.0,
            um_handoff_key: str = "proud"):
    """Proud UM bore, including the Option-B floor trunk when selected."""
    if ROUTING_PROFILE != "proud" or raceway_only:
        raise RuntimeError("external Obi-Wan raceway generation was removed")
    if radial_extra_mm < 0.0:
        raise ValueError("UM expansion must be non-negative")
    if STAND_FOOT:
        return _proud_floor_round_cutter(
            "um",
            um_handoff_key=um_handoff_key,
            radial_extra_mm=radial_extra_mm,
        )
    if not STAND_FOOT:
        points, radii = _stock_slim_no_floor_um_sections(
            um_handoff_key=um_handoff_key,
            radial_extra_mm=radial_extra_mm,
        )
        return _tube_loft(points, radii, sides=24)
    raise AssertionError("unreachable UM stand-state branch")


def _lm_tube_sections(um_handoff_key: str = "proud",
                      spacing_mm: float = 2.0):
    """Centerline sections and smooth D8.2->D9 terminal flare radii."""
    plan = _lm_plan_spline(um_handoff_key=um_handoff_key)
    count = max(12, int(math.ceil(plan.length / spacing_mm)))
    points = [tuple(plan @ (index / count)) for index in range(count + 1)]
    distances = [0.0]
    for first, second in zip(points[:-1], points[1:]):
        distances.append(distances[-1] + math.dist(first, second))
    flare_start = max(0.0, distances[-1] - LM_EXIT_FLARE_LENGTH_MM)
    base_radius = CABLE_D["lm"] / 2.0
    exit_radius = LM_EXIT_D_MM / 2.0
    radii = []
    for distance in distances:
        u = min(1.0, max(
            0.0,
            (distance - flare_start)
            / max(LM_EXIT_FLARE_LENGTH_MM, 1.0e-12),
        ))
        smooth = u * u * (3.0 - 2.0 * u)
        radii.append(base_radius + (exit_radius - base_radius) * smooth)
    handoff = lm_handoff_points(
        n=32, um_handoff_key=um_handoff_key)
    points.extend(handoff[1:])
    radii.extend([exit_radius] * (len(handoff) - 1))
    return points, radii


def lm_tube(um_handoff_key: str = "proud",
            radial_extra_mm: float = 0.0):
    """One continuous LM cutter with its selected gradual floor/entry path."""
    if ROUTING_PROFILE != "proud":
        raise RuntimeError("the proud LM tube requires profile proud")
    if radial_extra_mm < 0.0:
        raise ValueError("LM expansion must be non-negative")
    if STAND_FOOT:
        return _proud_floor_round_cutter(
            "lm",
            um_handoff_key=um_handoff_key,
            radial_extra_mm=radial_extra_mm,
        )
    if not STAND_FOOT:
        points, radii = _stock_slim_no_floor_lm_sections(
            um_handoff_key=um_handoff_key,
            radial_extra_mm=radial_extra_mm,
        )
        return _tube_loft(points, radii, sides=24)
    raise AssertionError("unreachable LM stand-state branch")





def _plan_ts_section_face(px, py, tx, ty, zc, w2, h2):
    """One released TS polygon section on a plan-tangent normal plane."""
    pl = Plane(
        origin=(px, py, 0.0),
        x_dir=(-ty, tx, 0.0),
        z_dir=(tx, ty, 0.0),
    )
    points = [
        (w2 * math.cos(angle), zc + h2 * math.sin(angle))
        for angle in (
            2.0 * math.pi * index / 24.0 for index in range(24))
    ]
    points.append(points[0])
    return pl * make_face(Wire(Polyline(*points).edges()))


def _spatial_round_section_face(point, tangent, radius_mm: float):
    """One D-round polygon section normal to an arbitrary 3D tangent."""
    tangent = _normalized_xyz(tangent)
    if abs(tangent[2]) < 0.92:
        x_dir = (-tangent[1], tangent[0], 0.0)
        x_norm = math.hypot(x_dir[0], x_dir[1])
        x_dir = (x_dir[0] / x_norm, x_dir[1] / x_norm, 0.0)
    else:
        x_dir = (1.0, 0.0, 0.0)
    plane = Plane(origin=point, x_dir=x_dir, z_dir=tangent)
    points = [
        (radius_mm * math.cos(angle), radius_mm * math.sin(angle))
        for angle in (
            2.0 * math.pi * index / 24.0 for index in range(24))
    ]
    points.append(points[0])
    return plane * make_face(Wire(Polyline(*points).edges()))


def _ts_cutter_on_path(
    path,
    y_range=None,
    section_extra_mm: float = 0.0,
    center_z_fn=None,
    follow_3d_tangent: bool = False,
):
    """Build the TS ruled loft along one already-qualified plan path.

    Keeping the section generator separate from the released centerline lets
    an optional vase optimize only its local route while retaining the exact
    D6-to-oval section law.  ``path`` may be a spline, edge, or joined wire;
    only its global X/Y position and tangent are used because ``ts_section``
    remains the default owner of the duct's Z station and section dimensions.
    A local variant may supply ``center_z_fn(t, x, y, default_z)`` and request
    section planes normal to that resulting 3D centerline.  Defaults preserve
    the released plan-path behavior exactly.
    """
    if section_extra_mm < 0.0:
        raise ValueError("TS section expansion must be non-negative")
    n_st = max(6, int(path.length / 2.4))
    indices = list(range(n_st + 1))
    if y_range is not None:
        y_min, y_max = y_range
        in_range = [i for i in indices
                    if y_min <= float((path @ (i / n_st)).Y) <= y_max]
        if not in_range:
            raise ValueError(f"TS route does not cross y range {y_range}")
        if in_range != list(range(in_range[0], in_range[-1] + 1)):
            raise ValueError("TS route is not y-monotone in requested range")
        # Include one original ruled-loft cell beyond each requested
        # bound so the partial cutter crosses the split prism cleanly.
        i0 = max(0, in_range[0] - 1)
        i1 = min(n_st, in_range[-1] + 1)
        indices = list(range(i0, i1 + 1))
    stations = []
    for i in indices:
        t = i / n_st
        px, py, _pz = tuple(path @ t)
        tx, ty, _tz = tuple(path % t)
        nrm = math.hypot(tx, ty)
        tx, ty = tx / nrm, ty / nrm
        w2, h2, zc = ts_section(py)
        if center_z_fn is not None:
            zc = float(center_z_fn(t, px, py, zc))
        w2 += section_extra_mm
        h2 += section_extra_mm
        stations.append((t, px, py, tx, ty, zc, w2, h2))

    secs = []
    for station_index, station in enumerate(stations):
        _t, px, py, tx, ty, zc, w2, h2 = station
        if follow_3d_tangent:
            before = stations[max(0, station_index - 1)]
            after = stations[min(len(stations) - 1, station_index + 1)]
            tangent = (
                after[1] - before[1],
                after[2] - before[2],
                after[5] - before[5],
            )
            tangent_norm = math.sqrt(sum(value * value for value in tangent))
            tangent = tuple(value / tangent_norm for value in tangent)
            plan_norm = math.hypot(tangent[0], tangent[1])
            if plan_norm <= 1.0e-9:
                raise ValueError("TS 3D centerline cannot be vertical")
            x_dir = (-tangent[1] / plan_norm,
                     tangent[0] / plan_norm, 0.0)
            pl = Plane(
                origin=(px, py, zc), x_dir=x_dir, z_dir=tangent)
            pts = [(w2 * math.cos(a), h2 * math.sin(a))
                   for a in (2.0 * math.pi * k / 24.0
                             for k in range(24))]
        else:
            # plane y-axis = z_dir x x_dir = +Z for any plan tangent, so
            # the profile's v coordinate is GLOBAL z (station idiom)
            secs.append(_plan_ts_section_face(
                px, py, tx, ty, zc, w2, h2))
            continue
        pts.append(pts[0])
        secs.append(pl * make_face(Wire(Polyline(*pts).edges())))
    return loft(secs, ruled=True)


def ts_cutter_from_path(
    path,
    y_range=None,
    section_extra_mm: float = 0.0,
    center_z_fn=None,
    follow_3d_tangent: bool = False,
):
    """Public reuse hook for a locally optimized proud-family TS path.

    ``section_extra_mm`` expands both half-axes by a radial guard.  Production
    cutters leave it at zero; BREP containment checks use it to prove a real
    material skin around the complete duct instead of checking only its
    centerline.  ``center_z_fn`` and ``follow_3d_tangent`` are an explicit
    reuse hook for variants whose qualified local route changes Z smoothly.
    """
    if ROUTING_PROFILE != "proud":
        raise RuntimeError(
            "custom proud TS cutters require LX_ROUTING_PROFILE=proud")
    if float(path.length) <= 0.0:
        raise ValueError("custom TS path must have positive length")
    return _ts_cutter_on_path(
        path,
        y_range=y_range,
        section_extra_mm=section_extra_mm,
        center_z_fn=center_z_fn,
        follow_3d_tangent=follow_3d_tangent,
    )


def _ts_cutter(y_range=None, ts_route_key: str = TS_ROUTE_STANDARD):
    """The released TS duct as ONE ruled loft: vertical elliptical sections
    every ~2.4 mm along the interpolating spline of the route, sized
    and positioned by ts_section(y). Outside the vase every section
    is the O6.0 circle at z=11.5, so the solid matches the old pipe
    sweep there to within the chord sag (<0.03 on the r=116.5 arc).
    ONE solid because joining coaxial tubes (round sweep + oval loft)
    leaves near-tangent sliver faces at the join -- the exposed-duct/
    open-STL-edge failure class. Sections are 24-gons (inscribed:
    bore ~1% under nominal -- wall margins stay conservative)."""
    path = ts_plan_path(ts_route_key=ts_route_key)
    return _ts_cutter_on_path(path, y_range=y_range)


def _proud_floor_ts_complete_cutter(
        ts_route_key: str = TS_ROUTE_STANDARD,
        upper_y_range=None):
    """One ruled solid for the complete floor T trunk and upper TS route.

    The floor cubic and retained plan path meet at the released y=90 station
    with an exact common point, tangent, D6 section, and z=11.5 centre. A
    single loft keeps that junction internal to one solid; no tangent cutter
    union or overlapping sequential subtraction remains for OCC to fragment.
    """
    controls = proud_floor_entry_controls(
        "ts", ts_route_key=ts_route_key)
    lane = FOOT_LANES["ts"]
    service_start = (
        lane[0], lane[2], FLOOR_ROUTE_SERVICE_START_Z_MM)
    floor_path = Wire((Line(service_start, controls[0]), Bezier(*controls)))
    floor_count = max(
        12, int(math.ceil(float(floor_path.length) / 2.0)))
    radius = lane[4] / 2.0
    sections = [
        _spatial_round_section_face(
            tuple(floor_path @ (index / floor_count)),
            tuple(floor_path % (index / floor_count)),
            radius,
        )
        for index in range(floor_count + 1)
    ]

    main = ts_plan_path(ts_route_key=ts_route_key)
    join_parameter = _path_parameter_at_y(main, FLOOR_TS_JOIN_Y_MM)
    main_count = max(6, int(float(main.length) / 2.4))
    main_indices = [
        index for index in range(main_count + 1)
        if index / main_count > join_parameter + 1.0e-12
    ]
    if upper_y_range is not None and main_indices:
        _y_min, y_max = upper_y_range
        within = [
            index for index in main_indices
            if float((main @ (index / main_count)).Y) <= y_max
        ]
        if within:
            last_position = main_indices.index(within[-1])
            main_indices = main_indices[
                :min(len(main_indices), last_position + 2)]
        else:
            main_indices = []
    for index in main_indices:
        parameter = index / main_count
        point = main @ parameter
        tangent = main % parameter
        tx, ty = float(tangent.X), float(tangent.Y)
        tangent_norm = math.hypot(tx, ty)
        tx, ty = tx / tangent_norm, ty / tangent_norm
        px, py = float(point.X), float(point.Y)
        w2, h2, zc = ts_section(py)
        sections.append(_plan_ts_section_face(
            px, py, tx, ty, zc, w2, h2))

    cutter = loft(sections, ruled=True)
    solids = tuple(cutter.solids())
    if (not cutter.is_valid or len(solids) != 1
            or solids[0].volume <= 0.01):
        raise RuntimeError(
            "complete floor TS loft must be one valid solid; "
            f"valid={cutter.is_valid} volumes="
            f"{[solid.volume for solid in solids]}")
    cutter.label = "floor_ts_complete_single_loft"
    return cutter


def _entry_ramp(p0, p1, dia):
    """Straight oblique bore from outside the rear face (z<0) into the
    duct plane, along the arbitrary 3D axis p0 -> p1. Crosses z=0 at the
    rear breakout and overlaps the planar duct where it reaches z~5.5."""
    d = tuple(b - a for a, b in zip(p0, p1))
    length = math.dist(p0, p1)
    azimuth = math.degrees(math.atan2(d[1], d[0]))
    polar = math.degrees(math.acos(d[2] / length))
    mid = tuple((a + b) / 2.0 for a, b in zip(p0, p1))
    return (
        Pos(*mid)
        * Rot(Z=azimuth - 90.0)
        * Rot(X=-polar)
        * Cylinder(dia / 2.0, length)
    )


# Duct crossings of the glue seams: (x, y, z, duct r, plan extra).
# A vertical relief sphere widens each mouth laterally by the listed
# amount on both mating faces -- a funnel for the
# cross-seam fishing hand-off. Lateral only: z skins are untouched
# (the planar routing already guarantees vertical alignment). Nearest
# grown key pocket stays >=3.7 clear (seam B TS crossing binds).
SEAM_CROSSINGS = (
    (87.88, 120.0, 12.55, 3.9, 1.0),    # UM x seam A
    (-83.75, 120.0, 11.5, 3.0, 1.0),    # TS x seam A
    # The inward R6P spline crosses seam B here.  Only 0.1 mm of plan
    # funnel is needed; the old +1.0 sphere left <1 mm outer skin.
    (-33.3077, 315.95, 11.5, 3.0, 0.1),
)
SEAM_CROSSING_ROUTES = ("um", "ts", "ts")


def seam_relief_cutters(route_names=None):
    # Squashed SPHERES (plan r+extra, z-semi r-0.4): smooth everywhere,
    # so no wall/cap grazing against the bore -- flat-capped cylinders
    # left near-tangent slivers the mesher dropped (open STL edges
    # that read as an exposed duct; the historic mid_right bug), and the
    # foot-mode spline's <0.05 lateral shift made it intermittent.
    # Poles stay inside the bore (z-semi < r); z skins untouched.
    from build123d import Sphere, scale
    selected = (set(SEAM_CROSSING_ROUTES) if route_names is None
                else set(route_names))
    return [Pos(x, y, z) * scale(Sphere(r + extra),
                                 (1.0, 1.0,
                                  (r - 0.4) / (r + extra)))
            for route, (x, y, z, r, extra)
            in zip(SEAM_CROSSING_ROUTES, SEAM_CROSSINGS)
            if route in selected]


def cable_cutters(um_handoff_key: str = "proud", route_names=None,
                  ts_y_range=None,
                  ts_route_key: str = TS_ROUTE_STANDARD):
    """Build all proud cutters, or a spatially proven route subset.

    ``route_names`` is the low-memory split/export hook.  The default
    remains byte-for-byte the complete LM/UM/TS/t1f/t2f cutter set;
    callers may select only routes that can intersect one already-known
    split region so OCC never constructs the unrelated 4,800-face TS
    loft while exporting V1L mid-right. ``ts_route_key`` preserves the
    complete section and changes only the explicitly selected centerline.
    """
    if ROUTING_PROFILE != "proud":
        raise RuntimeError(
            "Obi-Wan routing is integral to its two carrier cores; "
            "cable_cutters() is only valid for LX_ROUTING_PROFILE=proud"
        )
    all_names = {"lm", "um", "ts", "t1f", "t2f"}
    selected = all_names if route_names is None else set(route_names)
    unknown = selected - all_names
    if unknown:
        raise ValueError(f"unknown cable route(s): {sorted(unknown)}")
    cutters = []
    cutters += seam_relief_cutters(selected)
    if "lm" in selected:
        cutters.append(lm_tube(um_handoff_key=um_handoff_key))
    if "um" in selected:
        cutters.append(um_tube(um_handoff_key=um_handoff_key))
    ts_cutter = None
    if "ts" in selected:
        effective_ts_y_range = ts_y_range
        if STAND_FOOT:
            lower = FLOOR_TS_JOIN_Y_MM - FLOOR_TS_JOIN_OVERLAP_MM
            if effective_ts_y_range is None:
                effective_ts_y_range = (lower, 1.0e9)
            else:
                effective_ts_y_range = (
                    max(lower, effective_ts_y_range[0]),
                    effective_ts_y_range[1],
                )
            if effective_ts_y_range[1] >= effective_ts_y_range[0]:
                if selected & {"t1f", "t2f"}:
                    ts_cutter = _proud_floor_ts_complete_cutter(
                        ts_route_key=ts_route_key,
                        upper_y_range=effective_ts_y_range,
                    )
                else:
                    ts_cutter = _ts_cutter(
                        y_range=effective_ts_y_range,
                        ts_route_key=ts_route_key)
        else:
            ts_cutter = _ts_cutter(
                y_range=effective_ts_y_range,
                ts_route_key=ts_route_key)
    if not STAND_FOOT:
        if selected & {"ts", "t1f", "t2f"}:
            if ts_cutter is not None:
                cutters.append(ts_cutter)
            cutters.append(no_floor_t_entry_cutter())
        elif ts_cutter is not None:
            cutters.append(ts_cutter)
        return cutters
    if ts_cutter is not None:
        cutters.append(ts_cutter)
    # One shared D6 T trunk replaces the former two small floor feeders.  Only
    # bottom/full callers request the feeder names; upper-only TS cutters do
    # not spend time constructing this disjoint floor sweep.
    if selected & {"t1f", "t2f"}:
        if "ts" not in selected:
            cutters.append(_proud_floor_round_cutter(
                "ts", ts_route_key=ts_route_key))
        elif ts_cutter is None:
            raise RuntimeError(
                "selected floor TS trunk has no complete cutter")
    return cutters
